// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="synth_execute_top_synth_execute_top,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.081000,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=861,HLS_SYN_LUT=1486,HLS_VERSION=2021_2}" *)

module synth_execute_top (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        seed_uopc,
        seed_rs1,
        seed_rs2,
        observable,
        observable_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] seed_uopc;
input  [63:0] seed_rs1;
input  [63:0] seed_rs2;
output  [63:0] observable;
output   observable_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg observable_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] state_execute_alu_results_valid_1;
reg   [63:0] state_execute_alu_results_result_1;
reg   [0:0] state_issue_issued_valids_1;
reg   [7:0] state_issue_issued_uops_uopc_1;
reg   [0:0] state_issue_issued_uops_iq_type_1;
reg   [0:0] state_issue_issued_uops_rename_prs1_1;
reg   [1:0] state_issue_issued_uops_rename_prs2_1;
reg   [5:0] state_int_rf_address0;
reg    state_int_rf_ce0;
reg    state_int_rf_we0;
wire   [63:0] state_int_rf_q0;
reg   [5:0] state_int_rf_address1;
reg    state_int_rf_ce1;
reg    state_int_rf_we1;
wire   [63:0] state_int_rf_q1;
wire    grp_execute_module_fu_96_ap_start;
wire    grp_execute_module_fu_96_ap_done;
wire    grp_execute_module_fu_96_ap_idle;
wire    grp_execute_module_fu_96_ap_ready;
wire   [5:0] grp_execute_module_fu_96_state_int_rf_address0;
wire    grp_execute_module_fu_96_state_int_rf_ce0;
wire   [5:0] grp_execute_module_fu_96_state_int_rf_address1;
wire    grp_execute_module_fu_96_state_int_rf_ce1;
wire   [0:0] grp_execute_module_fu_96_state_execute_alu_results_valid_1_o;
wire    grp_execute_module_fu_96_state_execute_alu_results_valid_1_o_ap_vld;
wire   [63:0] grp_execute_module_fu_96_state_execute_alu_results_result_1;
wire    grp_execute_module_fu_96_state_execute_alu_results_result_1_ap_vld;
reg    grp_execute_module_fu_96_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 state_execute_alu_results_valid_1 = 1'd0;
#0 state_execute_alu_results_result_1 = 64'd0;
#0 state_issue_issued_valids_1 = 1'd0;
#0 state_issue_issued_uops_uopc_1 = 8'd0;
#0 state_issue_issued_uops_iq_type_1 = 1'd0;
#0 state_issue_issued_uops_rename_prs1_1 = 1'd0;
#0 state_issue_issued_uops_rename_prs2_1 = 2'd0;
#0 grp_execute_module_fu_96_ap_start_reg = 1'b0;
end

synth_execute_top_state_int_rf_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
state_int_rf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(state_int_rf_address0),
    .ce0(state_int_rf_ce0),
    .we0(state_int_rf_we0),
    .d0(seed_rs2),
    .q0(state_int_rf_q0),
    .address1(state_int_rf_address1),
    .ce1(state_int_rf_ce1),
    .we1(state_int_rf_we1),
    .d1(seed_rs1),
    .q1(state_int_rf_q1)
);

synth_execute_top_execute_module grp_execute_module_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_execute_module_fu_96_ap_start),
    .ap_done(grp_execute_module_fu_96_ap_done),
    .ap_idle(grp_execute_module_fu_96_ap_idle),
    .ap_ready(grp_execute_module_fu_96_ap_ready),
    .state_issue_issued_uops_uopc_1(state_issue_issued_uops_uopc_1),
    .state_issue_issued_valids_1(state_issue_issued_valids_1),
    .state_issue_issued_uops_iq_type_1(state_issue_issued_uops_iq_type_1),
    .state_issue_issued_uops_rename_prs1_1(state_issue_issued_uops_rename_prs1_1),
    .state_issue_issued_uops_rename_prs2_1(state_issue_issued_uops_rename_prs2_1),
    .state_int_rf_address0(grp_execute_module_fu_96_state_int_rf_address0),
    .state_int_rf_ce0(grp_execute_module_fu_96_state_int_rf_ce0),
    .state_int_rf_q0(state_int_rf_q0),
    .state_int_rf_address1(grp_execute_module_fu_96_state_int_rf_address1),
    .state_int_rf_ce1(grp_execute_module_fu_96_state_int_rf_ce1),
    .state_int_rf_q1(state_int_rf_q1),
    .state_execute_alu_results_valid_1_i(state_execute_alu_results_valid_1),
    .state_execute_alu_results_valid_1_o(grp_execute_module_fu_96_state_execute_alu_results_valid_1_o),
    .state_execute_alu_results_valid_1_o_ap_vld(grp_execute_module_fu_96_state_execute_alu_results_valid_1_o_ap_vld),
    .state_execute_alu_results_result_1(grp_execute_module_fu_96_state_execute_alu_results_result_1),
    .state_execute_alu_results_result_1_ap_vld(grp_execute_module_fu_96_state_execute_alu_results_result_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_execute_module_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_execute_module_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_execute_module_fu_96_ap_ready == 1'b1)) begin
            grp_execute_module_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_execute_alu_results_result_1 <= 64'd0;
    end else if (((grp_execute_module_fu_96_state_execute_alu_results_result_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        state_execute_alu_results_result_1 <= grp_execute_module_fu_96_state_execute_alu_results_result_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_execute_alu_results_valid_1 <= 1'd0;
    end else if (((grp_execute_module_fu_96_state_execute_alu_results_valid_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        state_execute_alu_results_valid_1 <= grp_execute_module_fu_96_state_execute_alu_results_valid_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_issue_issued_uops_iq_type_1 <= 1'd1;
        state_issue_issued_uops_rename_prs1_1 <= 1'd1;
        state_issue_issued_uops_rename_prs2_1[1] <= 1'b1;
        state_issue_issued_uops_uopc_1 <= seed_uopc;
        state_issue_issued_valids_1 <= 1'd1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_execute_module_fu_96_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        observable_ap_vld = 1'b1;
    end else begin
        observable_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        state_int_rf_address0 = 6'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_int_rf_address0 = grp_execute_module_fu_96_state_int_rf_address0;
    end else begin
        state_int_rf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        state_int_rf_address1 = 6'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_int_rf_address1 = grp_execute_module_fu_96_state_int_rf_address1;
    end else begin
        state_int_rf_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_int_rf_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_int_rf_ce0 = grp_execute_module_fu_96_state_int_rf_ce0;
    end else begin
        state_int_rf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_int_rf_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_int_rf_ce1 = grp_execute_module_fu_96_state_int_rf_ce1;
    end else begin
        state_int_rf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_int_rf_we0 = 1'b1;
    end else begin
        state_int_rf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_int_rf_we1 = 1'b1;
    end else begin
        state_int_rf_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_execute_module_fu_96_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign grp_execute_module_fu_96_ap_start = grp_execute_module_fu_96_ap_start_reg;

assign observable = state_execute_alu_results_result_1;

always @ (posedge ap_clk) begin
    state_issue_issued_uops_rename_prs2_1[0] <= 1'b0;
end

endmodule //synth_execute_top
