#include "boom_config.hpp"
#include "boom_state.hpp"
#include "boom_interfaces.hpp"
#include "reset.hpp"
#include "completion.hpp"
#include <cstdio>

namespace boom { void rob_allocate(BoomCoreState&); void rob_complete(BoomCoreState&); void issue_module(BoomCoreState&); void execute_module(BoomCoreState&); void lsu_module(BoomCoreState&,PipeSignals&); void rob_commit_module(BoomCoreState&,PipeSignals&); }

static int passed=0, failed=0;
#define TEST(n) std::printf("  [W3 completion] %-46s ... ", n)
#define CHECK(c,m) do { if (!(c)) { std::printf("FAIL: %s\n",m); failed++; return; } } while (0)
#define PASS() do { std::printf("PASS\n"); passed++; } while (0)

static ExecuteState::AluResult result(uint8_t rob, uint64_t value, uint8_t pdst=0) {
    ExecuteState::AluResult r; r.valid=true; r.uop.queue.rob_idx=rob; r.result=value; r.uop.uopc=1;
    r.uop.iq_type=IQ_ALU; r.uop.fu_code=FU_ALU; r.uop.rename.pdst=pdst; r.uop.rename.dst_rtype=pdst?DST_INT:DST_N; return r;
}
static void rob_entry(BoomCoreState& s,uint8_t idx) { s.rob.entries[idx]=RobEntry(); s.rob.entries[idx].valid=true; s.rob.entries[idx].busy=true; s.rob.entries[idx].uop.queue.rob_idx=idx; }
static void load_result(BoomCoreState& s,uint8_t rob) { s.execute.alu_results[0]=result(rob,0); ExecuteState::AluResult& r=s.execute.alu_results[0]; r.memory_valid=true;r.is_load=true;r.uop.uopc=42;r.uop.ctrl.is_load=true;r.uop.mem.uses_ldq=true;r.memory_size=3;r.memory_mask=0xff;r.memory_address=0x40; }
static void store_result(BoomCoreState& s,uint8_t rob) { s.execute.alu_results[0]=result(rob,0); ExecuteState::AluResult& r=s.execute.alu_results[0]; r.memory_valid=true;r.is_store=true;r.uop.uopc=49;r.uop.ctrl.is_sta=true;r.uop.mem.uses_stq=true;r.memory_size=3;r.memory_mask=0xff;r.memory_address=0x48;r.store_data=7; }

static void t01(){TEST("services two nonwriting completions");BoomCoreState s;rob_entry(s,1);rob_entry(s,2);s.execute.alu_results[0]=result(1,1);s.execute.alu_results[1]=result(2,2);boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&!s.execute.alu_results[1].valid&&!s.rob.entries[1].busy&&!s.rob.entries[2].busy&&s.completion.rob_completes_this_cycle==2,"two nonwriters did not complete");PASS();}
static void t02(){TEST("ROB age permits cumulative completion");BoomCoreState s;s.rob.head=4;rob_entry(s,4);rob_entry(s,5);s.execute.alu_results[0]=result(5,5);s.execute.alu_results[1]=result(4,4);boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&!s.execute.alu_results[1].valid&&!s.rob.entries[4].busy&&!s.rob.entries[5].busy,"cumulative age service failed");PASS();}
static void t03(){TEST("ROB wrap cumulative service is safe");BoomCoreState s;s.rob.head=31;rob_entry(s,31);rob_entry(s,0);s.execute.alu_results[0]=result(0,0);s.execute.alu_results[1]=result(31,31);boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&!s.execute.alu_results[1].valid&&!s.rob.entries[31].busy&&!s.rob.entries[0].busy,"wrap cumulative service failed");PASS();}
static void t04(){TEST("completion performs sole integer writeback");BoomCoreState s;rob_entry(s,1);s.rename.int_free_list.busy_table[6]=true;s.execute.alu_results[1]=result(1,0x1234,6);boom::rob_complete(s);CHECK(boom::prf_read(s,6)==0x1234&&!s.rename.int_free_list.busy_table[6]&&!s.rob.entries[1].busy,"writeback incomplete");PASS();}
static void t05(){TEST("full LDQ retains MEM completion stable");BoomCoreState s;rob_entry(s,1);load_result(s,1);s.lsu.ldq_count=LDQ_DEPTH;ExecuteState::AluResult before=s.execute.alu_results[0];boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&s.completion.mem_execute.valid&&s.completion.mem_execute.memory_address==before.memory_address&&s.rob.entries[1].busy,"blocked load changed");PASS();}
static void t06(){TEST("load atomically enters LDQ");BoomCoreState s;rob_entry(s,1);load_result(s,1);boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&s.lsu.ldq_count==1&&s.rob.entries[1].memory_valid&&s.rob.entries[1].busy,"load admission not atomic");PASS();}
static void t07(){TEST("full STQ retains store completion stable");BoomCoreState s;rob_entry(s,1);store_result(s,1);s.lsu.stq_count=STQ_DEPTH;boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&s.completion.mem_execute.valid&&s.rob.entries[1].busy,"blocked store changed");PASS();}
static void t08(){TEST("store atomically enters STQ and completes ROB");BoomCoreState s;rob_entry(s,1);store_result(s,1);boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&s.lsu.stq_count==1&&!s.rob.entries[1].busy&&s.rob.entries[1].memory_valid,"store admission wrong");PASS();}
static void t09(){TEST("LDQ reclaimed after matching response");BoomCoreState s;rob_entry(s,1);load_result(s,1);s.execute.alu_results[0].uop.rename.pdst=7;s.execute.alu_results[0].uop.rename.dst_rtype=DST_INT;s.rob.entries[1].uop=s.execute.alu_results[0].uop;boom::rob_complete(s);PipeSignals p;boom::lsu_module(s,p);CHECK(s.lsu.load_response_pending,"load request not issued");DmemResponse d;d.transaction_id=s.lsu.pending_load_transaction_id;d.data=9;d.read_data=9;p.dmem_resp.write(d);boom::completion_service_cycle(s,p);CHECK(s.lsu.ldq_count==0&&!s.rob.entries[1].busy&&boom::prf_read(s,7)==9,"LDQ not reclaimed");PASS();}
static void t10(){TEST("STQ reclaimed after committed request");BoomCoreState s;s.rob.head=1;s.rob.tail=2;rob_entry(s,1);store_result(s,1);s.rob.entries[1].uop=s.execute.alu_results[0].uop;boom::rob_complete(s);PipeSignals p;boom::rob_commit_module(s,p);CHECK(s.lsu.stq_count==0&&!p.dmem_req.empty()&&s.rob.commit_valid,"STQ not reclaimed at request");PASS();}
static void t11(){TEST("branch resolves before ROB busy clear");BoomCoreState s;s.rob.head=1;rob_entry(s,1);s.branch_state.active_mask=1;s.branch_state.tag_valid[0]=true;s.execute.alu_results[1]=result(1,0);s.execute.alu_results[1].uop.branch.is_br=true;s.execute.alu_results[1].uop.branch.br_tag=0;boom::rob_complete(s);CHECK(s.brupdate.valid&&!s.rob.entries[1].busy&&!s.execute.alu_results[1].valid,"branch completion order wrong");PASS();}
static void t12(){TEST("mispredict kills younger held completion");BoomCoreState s;s.rob.head=1;rob_entry(s,1);rob_entry(s,2);s.rob.tail=3;s.branch_state.active_mask=1;s.branch_state.tag_valid[0]=true;s.branch_state.snapshot_valid[0]=true;s.execute.alu_results[0]=result(2,2);s.execute.alu_results[0].uop.branch.br_mask=1;s.execute.alu_results[1]=result(1,1);s.execute.alu_results[1].uop.branch.is_br=true;s.execute.alu_results[1].uop.branch.br_tag=0;s.execute.alu_results[1].mispredict=true;boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&!s.rob.entries[2].valid&&s.brupdate.mispredict,"younger completion survived");PASS();}
static void t13(){TEST("reset kills both held completions");BoomCoreState s;s.execute.alu_results[0]=result(1,1);s.execute.alu_results[1]=result(2,2);ResetControllerState rc;boom_core_reset_step(s,rc);CHECK(!s.execute.alu_results[0].valid&&!s.execute.alu_results[1].valid,"reset retained completion");PASS();}
static void t14(){TEST("trace backpressure makes commit atomic");BoomCoreState s;s.rob.head=1;s.rob.tail=2;rob_entry(s,1);s.rob.entries[1].busy=false;s.rob.entries[1].uop.uopc=1;PipeSignals p;CommitEntry ce;for(int i=0;i<1024;i++)p.commit_trace.write(ce);uint64_t old=s.csr.instret;boom::rob_commit_module(s,p);CHECK(s.rob.entries[1].valid&&s.csr.instret==old&&!s.rob.commit_valid,"trace-full commit mutated state");PASS();}
static void t15(){TEST("DMEM backpressure makes store commit atomic");BoomCoreState s;s.rob.head=1;s.rob.tail=2;rob_entry(s,1);store_result(s,1);boom::rob_complete(s);s.rob.entries[1].uop.uopc=49;s.rob.entries[1].uop.ctrl.is_sta=true;s.rob.entries[1].uop.queue.rob_idx=1;PipeSignals p;DmemRequest req;for(int i=0;i<1024;i++)p.dmem_req.write(req);boom::rob_commit_module(s,p);CHECK(s.rob.entries[1].valid&&!s.rob.entries[1].memory_request_sent&&s.lsu.stq_count==1&&p.commit_trace.empty(),"DMEM-full commit mutated state");PASS();}
static void t16(){TEST("ROB identity propagates exactly once to execute");BoomCoreState s;s.rename.dispatch_packets[0].valid=true;s.rename.dispatch_packets[0].uop.uopc=1;s.rename.dispatch_packets[0].uop.iq_type=IQ_ALU;s.rename.dispatch_packets[0].uop.fu_code=FU_ALU;boom::rob_allocate(s);uint32_t id=s.rename.dispatch_packets[0].uop.queue.rob_allocation_id;uint32_t next=s.rob.next_allocation_id;boom::rob_allocate(s);CHECK(id!=0&&s.rob.entries[0].uop.queue.rob_allocation_id==id&&s.rob.next_allocation_id==next,"allocation identity changed on retry");s.issue.port_ready[INT_ISSUE_LANE]=false;boom::issue_module(s);CHECK(s.issue.alu_iq.count==1&&s.issue.alu_iq.entries[0].uop.queue.rob_allocation_id==id,"identity lost at IQ dispatch");s.issue.port_ready[INT_ISSUE_LANE]=true;boom::issue_module(s);CHECK(s.issue.issued_valids[INT_ISSUE_LANE]&&s.issue.issued_uops[INT_ISSUE_LANE].queue.rob_allocation_id==id,"identity lost at issue");boom::execute_module(s);CHECK(s.execute.alu_results[INT_ISSUE_LANE].valid&&s.execute.alu_results[INT_ISSUE_LANE].uop.queue.rob_allocation_id==id,"identity lost at execute");PASS();}
static void t17(){TEST("stale held completion cannot alias reused ROB index");BoomCoreState s;rob_entry(s,3);s.rob.entries[3].uop.queue.rob_allocation_id=22;s.execute.alu_results[0]=result(3,0xdead,7);s.execute.alu_results[0].uop.queue.rob_allocation_id=21;s.execute.alu_results[0].uop.branch.is_br=true;s.execute.alu_results[0].uop.branch.br_tag=0;s.execute.alu_results[0].is_store=true;s.execute.alu_results[0].memory_valid=true;s.execute.alu_results[0].exception=true;s.rename.int_free_list.busy_table[7]=true;boom::rob_complete(s);CHECK(!s.execute.alu_results[0].valid&&s.rob.entries[3].busy&&!s.rob.entries[3].exception&&s.lsu.stq_count==0&&!s.brupdate.valid&&boom::prf_read(s,7)==0&&s.rename.int_free_list.busy_table[7],"stale completion caused side effect");PASS();}
static void t18(){TEST("pre-reset load response cannot alias new load");BoomCoreState s;rob_entry(s,1);s.rob.entries[1].uop.queue.rob_allocation_id=31;load_result(s,1);s.execute.alu_results[0].uop.queue.rob_allocation_id=31;s.execute.alu_results[0].uop.rename.pdst=8;s.execute.alu_results[0].uop.rename.dst_rtype=DST_INT;s.rob.entries[1].uop=s.execute.alu_results[0].uop;boom::rob_complete(s);PipeSignals p;boom::lsu_module(s,p);uint32_t stale_tx=s.lsu.pending_load_transaction_id;ResetControllerState rc;for(int i=0;!rc.completed&&i<200;i++)boom_core_reset_step(s,rc);rob_entry(s,1);s.rob.entries[1].uop.queue.rob_allocation_id=32;load_result(s,1);s.execute.alu_results[0].uop.queue.rob_allocation_id=32;s.execute.alu_results[0].uop.rename.pdst=9;s.execute.alu_results[0].uop.rename.dst_rtype=DST_INT;s.rob.entries[1].uop=s.execute.alu_results[0].uop;boom::rob_complete(s);boom::lsu_module(s,p);uint32_t new_tx=s.lsu.pending_load_transaction_id;CHECK(new_tx!=stale_tx,"transaction ID reused across reset");DmemResponse stale;stale.transaction_id=stale_tx;stale.data=0xdead;p.dmem_resp.write(stale);boom::completion_service_cycle(s,p);CHECK(s.lsu.load_response_pending&&s.rob.entries[1].busy&&boom::prf_read(s,9)==0,"stale response completed new load");DmemResponse fresh;fresh.transaction_id=new_tx;fresh.data=0xbeef;p.dmem_resp.write(fresh);boom::completion_service_cycle(s,p);CHECK(!s.lsu.load_response_pending&&!s.rob.entries[1].busy&&boom::prf_read(s,9)==0xbeef,"new response did not complete new load");PASS();}

int main(){std::printf("=== W3 Conservative Completion Buffer Tests ===\n");t01();t02();t03();t04();t05();t06();t07();t08();t09();t10();t11();t12();t13();t14();t15();t16();t17();t18();std::printf("W3 completion buffer: %d passed, %d failed\n",passed,failed);return failed?1:0;}
