// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module boom_core_top_rob_allocate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_rob_state_i,
        state_rob_state_o,
        state_rob_state_o_ap_vld,
        state_rename_dispatch_packets_valid_0,
        state_rename_dispatch_packets_rob_allocated_0_i,
        state_rename_dispatch_packets_rob_allocated_0_o,
        state_rename_dispatch_packets_rob_allocated_0_o_ap_vld,
        state_rob_head,
        state_rob_tail_i,
        state_rob_tail_o,
        state_rob_tail_o_ap_vld,
        state_rob_maybe_full_i,
        state_rob_maybe_full_o,
        state_rob_maybe_full_o_ap_vld,
        state_rename_dispatch_packets_uop_uopc_0,
        state_rename_dispatch_packets_uop_inst_0,
        state_rename_dispatch_packets_uop_debug_pc_0,
        state_rename_dispatch_packets_uop_ctrl_is_load_0,
        state_rename_dispatch_packets_uop_ctrl_is_sta_0,
        state_rename_dispatch_packets_uop_branch_br_mask_0,
        state_rename_dispatch_packets_uop_rename_ldst_0,
        state_rename_dispatch_packets_uop_rename_pdst_0,
        state_rename_dispatch_packets_uop_rename_stale_pdst_0,
        state_rename_dispatch_packets_uop_rename_dst_rtype_0,
        state_rename_dispatch_packets_uop_exception_0,
        state_rob_entries_memory_valid_address0,
        state_rob_entries_memory_valid_ce0,
        state_rob_entries_memory_valid_we0,
        state_rob_entries_memory_valid_d0,
        state_rob_entries_is_load_address0,
        state_rob_entries_is_load_ce0,
        state_rob_entries_is_load_we0,
        state_rob_entries_is_load_d0,
        state_rob_entries_is_store_address0,
        state_rob_entries_is_store_ce0,
        state_rob_entries_is_store_we0,
        state_rob_entries_is_store_d0,
        state_rob_entries_signed_load_address0,
        state_rob_entries_signed_load_ce0,
        state_rob_entries_signed_load_we0,
        state_rob_entries_signed_load_d0,
        state_rob_entries_memory_request_sent_address0,
        state_rob_entries_memory_request_sent_ce0,
        state_rob_entries_memory_request_sent_we0,
        state_rob_entries_memory_request_sent_d0,
        state_rob_entries_memory_completed_address0,
        state_rob_entries_memory_completed_ce0,
        state_rob_entries_memory_completed_we0,
        state_rob_entries_memory_completed_d0,
        state_rob_entries_memory_address_address0,
        state_rob_entries_memory_address_ce0,
        state_rob_entries_memory_address_we0,
        state_rob_entries_memory_address_d0,
        state_rob_entries_memory_data_address0,
        state_rob_entries_memory_data_ce0,
        state_rob_entries_memory_data_we0,
        state_rob_entries_memory_data_d0,
        state_rob_entries_memory_mask_address0,
        state_rob_entries_memory_mask_ce0,
        state_rob_entries_memory_mask_we0,
        state_rob_entries_memory_mask_d0,
        state_rob_entries_memory_size_address0,
        state_rob_entries_memory_size_ce0,
        state_rob_entries_memory_size_we0,
        state_rob_entries_memory_size_d0,
        state_rob_entries_memory_transaction_id_address0,
        state_rob_entries_memory_transaction_id_ce0,
        state_rob_entries_memory_transaction_id_we0,
        state_rob_entries_memory_transaction_id_d0,
        state_rob_entries_valid_address0,
        state_rob_entries_valid_ce0,
        state_rob_entries_valid_we0,
        state_rob_entries_valid_d0,
        state_rob_entries_busy_address0,
        state_rob_entries_busy_ce0,
        state_rob_entries_busy_we0,
        state_rob_entries_busy_d0,
        state_rob_entries_exception_address0,
        state_rob_entries_exception_ce0,
        state_rob_entries_exception_we0,
        state_rob_entries_exception_d0,
        state_rob_entries_uop_uopc_address0,
        state_rob_entries_uop_uopc_ce0,
        state_rob_entries_uop_uopc_we0,
        state_rob_entries_uop_uopc_d0,
        state_rob_entries_uop_inst_address0,
        state_rob_entries_uop_inst_ce0,
        state_rob_entries_uop_inst_we0,
        state_rob_entries_uop_inst_d0,
        state_rob_entries_uop_debug_pc_address0,
        state_rob_entries_uop_debug_pc_ce0,
        state_rob_entries_uop_debug_pc_we0,
        state_rob_entries_uop_debug_pc_d0,
        state_rob_entries_uop_ctrl_is_load_address0,
        state_rob_entries_uop_ctrl_is_load_ce0,
        state_rob_entries_uop_ctrl_is_load_we0,
        state_rob_entries_uop_ctrl_is_load_d0,
        state_rob_entries_uop_ctrl_is_sta_address0,
        state_rob_entries_uop_ctrl_is_sta_ce0,
        state_rob_entries_uop_ctrl_is_sta_we0,
        state_rob_entries_uop_ctrl_is_sta_d0,
        state_rob_entries_uop_branch_br_mask_address0,
        state_rob_entries_uop_branch_br_mask_ce0,
        state_rob_entries_uop_branch_br_mask_we0,
        state_rob_entries_uop_branch_br_mask_d0,
        state_rob_entries_uop_queue_rob_idx_address0,
        state_rob_entries_uop_queue_rob_idx_ce0,
        state_rob_entries_uop_queue_rob_idx_we0,
        state_rob_entries_uop_queue_rob_idx_d0,
        state_rob_entries_uop_queue_rob_allocation_id_address0,
        state_rob_entries_uop_queue_rob_allocation_id_ce0,
        state_rob_entries_uop_queue_rob_allocation_id_we0,
        state_rob_entries_uop_queue_rob_allocation_id_d0,
        state_rob_entries_uop_rename_ldst_address0,
        state_rob_entries_uop_rename_ldst_ce0,
        state_rob_entries_uop_rename_ldst_we0,
        state_rob_entries_uop_rename_ldst_d0,
        state_rob_entries_uop_rename_pdst_address0,
        state_rob_entries_uop_rename_pdst_ce0,
        state_rob_entries_uop_rename_pdst_we0,
        state_rob_entries_uop_rename_pdst_d0,
        state_rob_entries_uop_rename_stale_pdst_address0,
        state_rob_entries_uop_rename_stale_pdst_ce0,
        state_rob_entries_uop_rename_stale_pdst_we0,
        state_rob_entries_uop_rename_stale_pdst_d0,
        state_rob_entries_uop_rename_dst_rtype_address0,
        state_rob_entries_uop_rename_dst_rtype_ce0,
        state_rob_entries_uop_rename_dst_rtype_we0,
        state_rob_entries_uop_rename_dst_rtype_d0,
        state_rename_dispatch_packets_uop_queue_rob_idx_0,
        state_rename_dispatch_packets_uop_queue_rob_idx_0_ap_vld,
        state_rename_dispatch_packets_uop_queue_rob_allocation_id_0,
        state_rename_dispatch_packets_uop_queue_rob_allocation_id_0_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] state_rob_state_i;
output  [1:0] state_rob_state_o;
output   state_rob_state_o_ap_vld;
input  [0:0] state_rename_dispatch_packets_valid_0;
input  [0:0] state_rename_dispatch_packets_rob_allocated_0_i;
output  [0:0] state_rename_dispatch_packets_rob_allocated_0_o;
output   state_rename_dispatch_packets_rob_allocated_0_o_ap_vld;
input  [4:0] state_rob_head;
input  [4:0] state_rob_tail_i;
output  [4:0] state_rob_tail_o;
output   state_rob_tail_o_ap_vld;
input  [0:0] state_rob_maybe_full_i;
output  [0:0] state_rob_maybe_full_o;
output   state_rob_maybe_full_o_ap_vld;
input  [7:0] state_rename_dispatch_packets_uop_uopc_0;
input  [31:0] state_rename_dispatch_packets_uop_inst_0;
input  [63:0] state_rename_dispatch_packets_uop_debug_pc_0;
input  [0:0] state_rename_dispatch_packets_uop_ctrl_is_load_0;
input  [0:0] state_rename_dispatch_packets_uop_ctrl_is_sta_0;
input  [7:0] state_rename_dispatch_packets_uop_branch_br_mask_0;
input  [4:0] state_rename_dispatch_packets_uop_rename_ldst_0;
input  [7:0] state_rename_dispatch_packets_uop_rename_pdst_0;
input  [7:0] state_rename_dispatch_packets_uop_rename_stale_pdst_0;
input  [1:0] state_rename_dispatch_packets_uop_rename_dst_rtype_0;
input  [0:0] state_rename_dispatch_packets_uop_exception_0;
output  [4:0] state_rob_entries_memory_valid_address0;
output   state_rob_entries_memory_valid_ce0;
output   state_rob_entries_memory_valid_we0;
output  [0:0] state_rob_entries_memory_valid_d0;
output  [4:0] state_rob_entries_is_load_address0;
output   state_rob_entries_is_load_ce0;
output   state_rob_entries_is_load_we0;
output  [0:0] state_rob_entries_is_load_d0;
output  [4:0] state_rob_entries_is_store_address0;
output   state_rob_entries_is_store_ce0;
output   state_rob_entries_is_store_we0;
output  [0:0] state_rob_entries_is_store_d0;
output  [4:0] state_rob_entries_signed_load_address0;
output   state_rob_entries_signed_load_ce0;
output   state_rob_entries_signed_load_we0;
output  [0:0] state_rob_entries_signed_load_d0;
output  [4:0] state_rob_entries_memory_request_sent_address0;
output   state_rob_entries_memory_request_sent_ce0;
output   state_rob_entries_memory_request_sent_we0;
output  [0:0] state_rob_entries_memory_request_sent_d0;
output  [4:0] state_rob_entries_memory_completed_address0;
output   state_rob_entries_memory_completed_ce0;
output   state_rob_entries_memory_completed_we0;
output  [0:0] state_rob_entries_memory_completed_d0;
output  [4:0] state_rob_entries_memory_address_address0;
output   state_rob_entries_memory_address_ce0;
output   state_rob_entries_memory_address_we0;
output  [63:0] state_rob_entries_memory_address_d0;
output  [4:0] state_rob_entries_memory_data_address0;
output   state_rob_entries_memory_data_ce0;
output   state_rob_entries_memory_data_we0;
output  [63:0] state_rob_entries_memory_data_d0;
output  [4:0] state_rob_entries_memory_mask_address0;
output   state_rob_entries_memory_mask_ce0;
output   state_rob_entries_memory_mask_we0;
output  [4:0] state_rob_entries_memory_mask_d0;
output  [4:0] state_rob_entries_memory_size_address0;
output   state_rob_entries_memory_size_ce0;
output   state_rob_entries_memory_size_we0;
output  [7:0] state_rob_entries_memory_size_d0;
output  [4:0] state_rob_entries_memory_transaction_id_address0;
output   state_rob_entries_memory_transaction_id_ce0;
output   state_rob_entries_memory_transaction_id_we0;
output  [31:0] state_rob_entries_memory_transaction_id_d0;
output  [4:0] state_rob_entries_valid_address0;
output   state_rob_entries_valid_ce0;
output   state_rob_entries_valid_we0;
output  [0:0] state_rob_entries_valid_d0;
output  [4:0] state_rob_entries_busy_address0;
output   state_rob_entries_busy_ce0;
output   state_rob_entries_busy_we0;
output  [0:0] state_rob_entries_busy_d0;
output  [4:0] state_rob_entries_exception_address0;
output   state_rob_entries_exception_ce0;
output   state_rob_entries_exception_we0;
output  [0:0] state_rob_entries_exception_d0;
output  [4:0] state_rob_entries_uop_uopc_address0;
output   state_rob_entries_uop_uopc_ce0;
output   state_rob_entries_uop_uopc_we0;
output  [7:0] state_rob_entries_uop_uopc_d0;
output  [4:0] state_rob_entries_uop_inst_address0;
output   state_rob_entries_uop_inst_ce0;
output   state_rob_entries_uop_inst_we0;
output  [31:0] state_rob_entries_uop_inst_d0;
output  [4:0] state_rob_entries_uop_debug_pc_address0;
output   state_rob_entries_uop_debug_pc_ce0;
output   state_rob_entries_uop_debug_pc_we0;
output  [63:0] state_rob_entries_uop_debug_pc_d0;
output  [4:0] state_rob_entries_uop_ctrl_is_load_address0;
output   state_rob_entries_uop_ctrl_is_load_ce0;
output   state_rob_entries_uop_ctrl_is_load_we0;
output  [0:0] state_rob_entries_uop_ctrl_is_load_d0;
output  [4:0] state_rob_entries_uop_ctrl_is_sta_address0;
output   state_rob_entries_uop_ctrl_is_sta_ce0;
output   state_rob_entries_uop_ctrl_is_sta_we0;
output  [0:0] state_rob_entries_uop_ctrl_is_sta_d0;
output  [4:0] state_rob_entries_uop_branch_br_mask_address0;
output   state_rob_entries_uop_branch_br_mask_ce0;
output   state_rob_entries_uop_branch_br_mask_we0;
output  [7:0] state_rob_entries_uop_branch_br_mask_d0;
output  [4:0] state_rob_entries_uop_queue_rob_idx_address0;
output   state_rob_entries_uop_queue_rob_idx_ce0;
output   state_rob_entries_uop_queue_rob_idx_we0;
output  [4:0] state_rob_entries_uop_queue_rob_idx_d0;
output  [4:0] state_rob_entries_uop_queue_rob_allocation_id_address0;
output   state_rob_entries_uop_queue_rob_allocation_id_ce0;
output   state_rob_entries_uop_queue_rob_allocation_id_we0;
output  [31:0] state_rob_entries_uop_queue_rob_allocation_id_d0;
output  [4:0] state_rob_entries_uop_rename_ldst_address0;
output   state_rob_entries_uop_rename_ldst_ce0;
output   state_rob_entries_uop_rename_ldst_we0;
output  [4:0] state_rob_entries_uop_rename_ldst_d0;
output  [4:0] state_rob_entries_uop_rename_pdst_address0;
output   state_rob_entries_uop_rename_pdst_ce0;
output   state_rob_entries_uop_rename_pdst_we0;
output  [7:0] state_rob_entries_uop_rename_pdst_d0;
output  [4:0] state_rob_entries_uop_rename_stale_pdst_address0;
output   state_rob_entries_uop_rename_stale_pdst_ce0;
output   state_rob_entries_uop_rename_stale_pdst_we0;
output  [7:0] state_rob_entries_uop_rename_stale_pdst_d0;
output  [4:0] state_rob_entries_uop_rename_dst_rtype_address0;
output   state_rob_entries_uop_rename_dst_rtype_ce0;
output   state_rob_entries_uop_rename_dst_rtype_we0;
output  [1:0] state_rob_entries_uop_rename_dst_rtype_d0;
output  [4:0] state_rename_dispatch_packets_uop_queue_rob_idx_0;
output   state_rename_dispatch_packets_uop_queue_rob_idx_0_ap_vld;
output  [31:0] state_rename_dispatch_packets_uop_queue_rob_allocation_id_0;
output   state_rename_dispatch_packets_uop_queue_rob_allocation_id_0_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] state_rob_state_o;
reg state_rob_state_o_ap_vld;
reg[0:0] state_rename_dispatch_packets_rob_allocated_0_o;
reg state_rename_dispatch_packets_rob_allocated_0_o_ap_vld;
reg[4:0] state_rob_tail_o;
reg state_rob_tail_o_ap_vld;
reg[0:0] state_rob_maybe_full_o;
reg state_rob_maybe_full_o_ap_vld;
reg state_rob_entries_memory_valid_ce0;
reg state_rob_entries_memory_valid_we0;
reg state_rob_entries_is_load_ce0;
reg state_rob_entries_is_load_we0;
reg state_rob_entries_is_store_ce0;
reg state_rob_entries_is_store_we0;
reg state_rob_entries_signed_load_ce0;
reg state_rob_entries_signed_load_we0;
reg state_rob_entries_memory_request_sent_ce0;
reg state_rob_entries_memory_request_sent_we0;
reg state_rob_entries_memory_completed_ce0;
reg state_rob_entries_memory_completed_we0;
reg state_rob_entries_memory_address_ce0;
reg state_rob_entries_memory_address_we0;
reg state_rob_entries_memory_data_ce0;
reg state_rob_entries_memory_data_we0;
reg state_rob_entries_memory_mask_ce0;
reg state_rob_entries_memory_mask_we0;
reg state_rob_entries_memory_size_ce0;
reg state_rob_entries_memory_size_we0;
reg state_rob_entries_memory_transaction_id_ce0;
reg state_rob_entries_memory_transaction_id_we0;
reg state_rob_entries_valid_ce0;
reg state_rob_entries_valid_we0;
reg state_rob_entries_busy_ce0;
reg state_rob_entries_busy_we0;
reg state_rob_entries_exception_ce0;
reg state_rob_entries_exception_we0;
reg state_rob_entries_uop_uopc_ce0;
reg state_rob_entries_uop_uopc_we0;
reg state_rob_entries_uop_inst_ce0;
reg state_rob_entries_uop_inst_we0;
reg state_rob_entries_uop_debug_pc_ce0;
reg state_rob_entries_uop_debug_pc_we0;
reg state_rob_entries_uop_ctrl_is_load_ce0;
reg state_rob_entries_uop_ctrl_is_load_we0;
reg state_rob_entries_uop_ctrl_is_sta_ce0;
reg state_rob_entries_uop_ctrl_is_sta_we0;
reg state_rob_entries_uop_branch_br_mask_ce0;
reg state_rob_entries_uop_branch_br_mask_we0;
reg state_rob_entries_uop_queue_rob_idx_ce0;
reg state_rob_entries_uop_queue_rob_idx_we0;
reg state_rob_entries_uop_queue_rob_allocation_id_ce0;
reg state_rob_entries_uop_queue_rob_allocation_id_we0;
reg state_rob_entries_uop_rename_ldst_ce0;
reg state_rob_entries_uop_rename_ldst_we0;
reg state_rob_entries_uop_rename_pdst_ce0;
reg state_rob_entries_uop_rename_pdst_we0;
reg state_rob_entries_uop_rename_stale_pdst_ce0;
reg state_rob_entries_uop_rename_stale_pdst_we0;
reg state_rob_entries_uop_rename_dst_rtype_ce0;
reg state_rob_entries_uop_rename_dst_rtype_we0;
reg state_rename_dispatch_packets_uop_queue_rob_idx_0_ap_vld;
reg state_rename_dispatch_packets_uop_queue_rob_allocation_id_0_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] state_rob_next_allocation_id;
wire   [63:0] zext_ln539_fu_607_p1;
wire   [0:0] state_rename_dispatch_packets_valid_0_load_load_fu_480_p1;
wire   [0:0] state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1;
wire   [0:0] is_full_load_fu_503_p1;
wire   [0:0] icmp_ln536_fu_562_p2;
wire   [0:0] icmp_ln533_fu_497_p2;
wire   [0:0] icmp_ln527_fu_468_p2;
wire   [4:0] add_ln548_fu_662_p2;
wire   [0:0] icmp_ln549_fu_674_p2;
wire   [31:0] select_ln538_fu_584_p3;
wire   [31:0] allocation_id_2_fu_598_p3;
wire   [0:0] icmp_ln538_fu_578_p2;
wire   [31:0] add_ln537_fu_572_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 state_rob_next_allocation_id = 32'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_next_allocation_id <= select_ln538_fu_584_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rename_dispatch_packets_rob_allocated_0_o = 1'd1;
    end else begin
        state_rename_dispatch_packets_rob_allocated_0_o = state_rename_dispatch_packets_rob_allocated_0_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rename_dispatch_packets_rob_allocated_0_o_ap_vld = 1'b1;
    end else begin
        state_rename_dispatch_packets_rob_allocated_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rename_dispatch_packets_uop_queue_rob_allocation_id_0_ap_vld = 1'b1;
    end else begin
        state_rename_dispatch_packets_uop_queue_rob_allocation_id_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rename_dispatch_packets_uop_queue_rob_idx_0_ap_vld = 1'b1;
    end else begin
        state_rename_dispatch_packets_uop_queue_rob_idx_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_busy_ce0 = 1'b1;
    end else begin
        state_rob_entries_busy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_busy_we0 = 1'b1;
    end else begin
        state_rob_entries_busy_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_exception_ce0 = 1'b1;
    end else begin
        state_rob_entries_exception_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_exception_we0 = 1'b1;
    end else begin
        state_rob_entries_exception_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_is_load_ce0 = 1'b1;
    end else begin
        state_rob_entries_is_load_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_is_load_we0 = 1'b1;
    end else begin
        state_rob_entries_is_load_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_is_store_ce0 = 1'b1;
    end else begin
        state_rob_entries_is_store_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_is_store_we0 = 1'b1;
    end else begin
        state_rob_entries_is_store_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_address_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_address_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_address_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_address_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_completed_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_completed_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_completed_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_completed_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_data_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_data_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_mask_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_mask_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_mask_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_mask_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_request_sent_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_request_sent_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_request_sent_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_request_sent_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_size_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_size_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_size_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_size_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_transaction_id_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_transaction_id_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_transaction_id_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_transaction_id_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_valid_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_memory_valid_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_valid_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_signed_load_ce0 = 1'b1;
    end else begin
        state_rob_entries_signed_load_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_signed_load_we0 = 1'b1;
    end else begin
        state_rob_entries_signed_load_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_branch_br_mask_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_branch_br_mask_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_branch_br_mask_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_branch_br_mask_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_ctrl_is_load_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_ctrl_is_load_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_ctrl_is_load_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_ctrl_is_load_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_ctrl_is_sta_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_ctrl_is_sta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_ctrl_is_sta_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_ctrl_is_sta_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_debug_pc_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_debug_pc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_debug_pc_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_debug_pc_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_inst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_inst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_inst_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_inst_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_queue_rob_allocation_id_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_queue_rob_allocation_id_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_queue_rob_allocation_id_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_queue_rob_allocation_id_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_queue_rob_idx_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_queue_rob_idx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_queue_rob_idx_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_queue_rob_idx_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_rename_dst_rtype_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_dst_rtype_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_rename_dst_rtype_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_dst_rtype_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_rename_ldst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_ldst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_rename_ldst_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_ldst_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_rename_pdst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_pdst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_rename_pdst_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_pdst_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_rename_stale_pdst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_stale_pdst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_rename_stale_pdst_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_stale_pdst_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_uopc_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_uopc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_uop_uopc_we0 = 1'b1;
    end else begin
        state_rob_entries_uop_uopc_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_valid_ce0 = 1'b1;
    end else begin
        state_rob_entries_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_entries_valid_we0 = 1'b1;
    end else begin
        state_rob_entries_valid_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (((icmp_ln549_fu_674_p2 == 1'd1) & (icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln549_fu_674_p2 == 1'd1) & (icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_maybe_full_o = 1'd1;
    end else begin
        state_rob_maybe_full_o = state_rob_maybe_full_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln549_fu_674_p2 == 1'd1) & (icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln549_fu_674_p2 == 1'd1) & (icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_maybe_full_o_ap_vld = 1'b1;
    end else begin
        state_rob_maybe_full_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln527_fu_468_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_state_o = 2'd1;
    end else begin
        state_rob_state_o = state_rob_state_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (icmp_ln527_fu_468_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_state_o_ap_vld = 1'b1;
    end else begin
        state_rob_state_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_tail_o = add_ln548_fu_662_p2;
    end else begin
        state_rob_tail_o = state_rob_tail_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_497_p2 == 1'd0) & (icmp_ln536_fu_562_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1)) | ((icmp_ln536_fu_562_p2 == 1'd0) & (is_full_load_fu_503_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 == 1'd1))))) begin
        state_rob_tail_o_ap_vld = 1'b1;
    end else begin
        state_rob_tail_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln537_fu_572_p2 = (state_rob_next_allocation_id + 32'd1);

assign add_ln548_fu_662_p2 = (state_rob_tail_i + 5'd1);

assign allocation_id_2_fu_598_p3 = ((icmp_ln538_fu_578_p2[0:0] == 1'b1) ? 32'd1 : state_rob_next_allocation_id);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign icmp_ln527_fu_468_p2 = ((state_rob_state_i == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln533_fu_497_p2 = ((state_rob_head == state_rob_tail_i) ? 1'b1 : 1'b0);

assign icmp_ln536_fu_562_p2 = ((state_rename_dispatch_packets_uop_uopc_0 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_578_p2 = ((state_rob_next_allocation_id == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln549_fu_674_p2 = ((add_ln548_fu_662_p2 == state_rob_head) ? 1'b1 : 1'b0);

assign is_full_load_fu_503_p1 = state_rob_maybe_full_i;

assign select_ln538_fu_584_p3 = ((icmp_ln538_fu_578_p2[0:0] == 1'b1) ? 32'd2 : add_ln537_fu_572_p2);

assign state_rename_dispatch_packets_rob_allocated_0_load_load_fu_484_p1 = state_rename_dispatch_packets_rob_allocated_0_i;

assign state_rename_dispatch_packets_uop_queue_rob_allocation_id_0 = allocation_id_2_fu_598_p3;

assign state_rename_dispatch_packets_uop_queue_rob_idx_0 = state_rob_tail_i;

assign state_rename_dispatch_packets_valid_0_load_load_fu_480_p1 = state_rename_dispatch_packets_valid_0;

assign state_rob_entries_busy_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_busy_d0 = (state_rename_dispatch_packets_uop_exception_0 ^ 1'd1);

assign state_rob_entries_exception_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_exception_d0 = state_rename_dispatch_packets_uop_exception_0;

assign state_rob_entries_is_load_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_is_load_d0 = 1'd0;

assign state_rob_entries_is_store_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_is_store_d0 = 1'd0;

assign state_rob_entries_memory_address_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_address_d0 = 64'd0;

assign state_rob_entries_memory_completed_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_completed_d0 = 1'd0;

assign state_rob_entries_memory_data_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_data_d0 = 64'd0;

assign state_rob_entries_memory_mask_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_mask_d0 = 5'd0;

assign state_rob_entries_memory_request_sent_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_request_sent_d0 = 1'd0;

assign state_rob_entries_memory_size_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_size_d0 = 8'd0;

assign state_rob_entries_memory_transaction_id_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_transaction_id_d0 = 32'd0;

assign state_rob_entries_memory_valid_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_memory_valid_d0 = 1'd0;

assign state_rob_entries_signed_load_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_signed_load_d0 = 1'd0;

assign state_rob_entries_uop_branch_br_mask_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_branch_br_mask_d0 = state_rename_dispatch_packets_uop_branch_br_mask_0;

assign state_rob_entries_uop_ctrl_is_load_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_ctrl_is_load_d0 = state_rename_dispatch_packets_uop_ctrl_is_load_0;

assign state_rob_entries_uop_ctrl_is_sta_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_ctrl_is_sta_d0 = state_rename_dispatch_packets_uop_ctrl_is_sta_0;

assign state_rob_entries_uop_debug_pc_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_debug_pc_d0 = state_rename_dispatch_packets_uop_debug_pc_0;

assign state_rob_entries_uop_inst_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_inst_d0 = state_rename_dispatch_packets_uop_inst_0;

assign state_rob_entries_uop_queue_rob_allocation_id_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_queue_rob_allocation_id_d0 = allocation_id_2_fu_598_p3;

assign state_rob_entries_uop_queue_rob_idx_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_queue_rob_idx_d0 = state_rob_tail_i;

assign state_rob_entries_uop_rename_dst_rtype_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_rename_dst_rtype_d0 = state_rename_dispatch_packets_uop_rename_dst_rtype_0;

assign state_rob_entries_uop_rename_ldst_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_rename_ldst_d0 = state_rename_dispatch_packets_uop_rename_ldst_0;

assign state_rob_entries_uop_rename_pdst_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_rename_pdst_d0 = state_rename_dispatch_packets_uop_rename_pdst_0;

assign state_rob_entries_uop_rename_stale_pdst_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_rename_stale_pdst_d0 = state_rename_dispatch_packets_uop_rename_stale_pdst_0;

assign state_rob_entries_uop_uopc_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_uop_uopc_d0 = state_rename_dispatch_packets_uop_uopc_0;

assign state_rob_entries_valid_address0 = zext_ln539_fu_607_p1;

assign state_rob_entries_valid_d0 = 1'd1;

assign zext_ln539_fu_607_p1 = state_rob_tail_i;

endmodule //boom_core_top_rob_allocate
