// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module synth_rob_top_rob_allocate (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_rename_dispatch_packets_valid_0,
        state_rename_dispatch_packets_uop_uopc_0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] state_rename_dispatch_packets_valid_0;
input  [4:0] state_rename_dispatch_packets_uop_uopc_0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] state_rob_state;
reg   [0:0] state_rename_dispatch_packets_rob_allocated_0;
reg   [4:0] state_rob_tail;
reg   [0:0] state_rob_maybe_full;
reg   [31:0] state_rob_next_allocation_id;
wire   [0:0] state_rob_state_load_load_fu_26_p1;
wire   [0:0] state_rename_dispatch_packets_valid_0_load_load_fu_36_p1;
wire   [0:0] state_rename_dispatch_packets_rob_allocated_0_load_load_fu_40_p1;
wire   [0:0] is_full_load_fu_54_p1;
wire   [0:0] icmp_ln536_fu_62_p2;
wire   [0:0] icmp_ln533_fu_48_p2;
wire   [4:0] add_ln548_fu_104_p2;
wire   [0:0] icmp_ln549_fu_116_p2;
wire   [31:0] select_ln538_fu_84_p3;
wire   [0:0] icmp_ln538_fu_78_p2;
wire   [31:0] add_ln537_fu_72_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 state_rob_state = 1'd0;
#0 state_rename_dispatch_packets_rob_allocated_0 = 1'd0;
#0 state_rob_tail = 5'd0;
#0 state_rob_maybe_full = 1'd0;
#0 state_rob_next_allocation_id = 32'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln533_fu_48_p2 == 1'd0) & (icmp_ln536_fu_62_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_40_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_36_p1 == 1'd1)) | ((icmp_ln536_fu_62_p2 == 1'd0) & (is_full_load_fu_54_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_40_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_36_p1 == 1'd1))))) begin
        state_rename_dispatch_packets_rob_allocated_0 <= 1'd1;
        state_rob_next_allocation_id <= select_ln538_fu_84_p3;
        state_rob_tail <= add_ln548_fu_104_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((icmp_ln549_fu_116_p2 == 1'd1) & (icmp_ln533_fu_48_p2 == 1'd0) & (icmp_ln536_fu_62_p2 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_40_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_36_p1 == 1'd1)) | ((icmp_ln549_fu_116_p2 == 1'd1) & (icmp_ln536_fu_62_p2 == 1'd0) & (is_full_load_fu_54_p1 == 1'd0) & (state_rename_dispatch_packets_rob_allocated_0_load_load_fu_40_p1 == 1'd0) & (state_rename_dispatch_packets_valid_0_load_load_fu_36_p1 == 1'd1))))) begin
        state_rob_maybe_full <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (state_rob_state_load_load_fu_26_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_state <= 1'd1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln537_fu_72_p2 = (state_rob_next_allocation_id + 32'd1);

assign add_ln548_fu_104_p2 = (state_rob_tail + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign icmp_ln533_fu_48_p2 = ((state_rob_tail == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln536_fu_62_p2 = ((state_rename_dispatch_packets_uop_uopc_0 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_78_p2 = ((state_rob_next_allocation_id == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln549_fu_116_p2 = ((add_ln548_fu_104_p2 == 5'd0) ? 1'b1 : 1'b0);

assign is_full_load_fu_54_p1 = state_rob_maybe_full;

assign select_ln538_fu_84_p3 = ((icmp_ln538_fu_78_p2[0:0] == 1'b1) ? 32'd2 : add_ln537_fu_72_p2);

assign state_rename_dispatch_packets_rob_allocated_0_load_load_fu_40_p1 = state_rename_dispatch_packets_rob_allocated_0;

assign state_rename_dispatch_packets_valid_0_load_load_fu_36_p1 = state_rename_dispatch_packets_valid_0;

assign state_rob_state_load_load_fu_26_p1 = state_rob_state;

endmodule //synth_rob_top_rob_allocate
