// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module boom_core_top_completion_is_valid (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        state_rob_entries_valid_address0,
        state_rob_entries_valid_ce0,
        state_rob_entries_valid_q0,
        state_rob_entries_uop_queue_rob_allocation_id_address0,
        state_rob_entries_uop_queue_rob_allocation_id_ce0,
        state_rob_entries_uop_queue_rob_allocation_id_q0,
        state_rob_entries_busy_address0,
        state_rob_entries_busy_ce0,
        state_rob_entries_busy_q0,
        state_rob_entries_memory_valid_address0,
        state_rob_entries_memory_valid_ce0,
        state_rob_entries_memory_valid_q0,
        state_rob_entries_memory_completed_address0,
        state_rob_entries_memory_completed_ce0,
        state_rob_entries_memory_completed_q0,
        state_rob_entries_is_load_address0,
        state_rob_entries_is_load_ce0,
        state_rob_entries_is_load_q0,
        state_rob_entries_memory_request_sent_address0,
        state_rob_entries_memory_request_sent_ce0,
        state_rob_entries_memory_request_sent_q0,
        state_rob_entries_memory_transaction_id_address0,
        state_rob_entries_memory_transaction_id_ce0,
        state_rob_entries_memory_transaction_id_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
output  [4:0] state_rob_entries_valid_address0;
output   state_rob_entries_valid_ce0;
input  [0:0] state_rob_entries_valid_q0;
output  [4:0] state_rob_entries_uop_queue_rob_allocation_id_address0;
output   state_rob_entries_uop_queue_rob_allocation_id_ce0;
input  [31:0] state_rob_entries_uop_queue_rob_allocation_id_q0;
output  [4:0] state_rob_entries_busy_address0;
output   state_rob_entries_busy_ce0;
input  [0:0] state_rob_entries_busy_q0;
output  [4:0] state_rob_entries_memory_valid_address0;
output   state_rob_entries_memory_valid_ce0;
input  [0:0] state_rob_entries_memory_valid_q0;
output  [4:0] state_rob_entries_memory_completed_address0;
output   state_rob_entries_memory_completed_ce0;
input  [0:0] state_rob_entries_memory_completed_q0;
output  [4:0] state_rob_entries_is_load_address0;
output   state_rob_entries_is_load_ce0;
input  [0:0] state_rob_entries_is_load_q0;
output  [4:0] state_rob_entries_memory_request_sent_address0;
output   state_rob_entries_memory_request_sent_ce0;
input  [0:0] state_rob_entries_memory_request_sent_q0;
output  [4:0] state_rob_entries_memory_transaction_id_address0;
output   state_rob_entries_memory_transaction_id_ce0;
input  [31:0] state_rob_entries_memory_transaction_id_q0;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg state_rob_entries_valid_ce0;
reg state_rob_entries_uop_queue_rob_allocation_id_ce0;
reg state_rob_entries_busy_ce0;
reg state_rob_entries_memory_valid_ce0;
reg state_rob_entries_memory_completed_ce0;
reg state_rob_entries_is_load_ce0;
reg state_rob_entries_memory_request_sent_ce0;
reg state_rob_entries_memory_transaction_id_ce0;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln577_fu_204_p2;
reg   [0:0] icmp_ln577_reg_473;
wire   [63:0] zext_ln577_fu_210_p1;
wire    ap_CS_fsm_state2;
wire   [2:0] tmp_fu_194_p4;
wire   [0:0] icmp_ln585_fu_234_p2;
wire   [0:0] xor_ln584_fu_222_p2;
wire   [0:0] or_ln577_1_fu_240_p2;
wire   [0:0] icmp_ln584_fu_228_p2;
wire   [0:0] or_ln577_fu_246_p2;
wire   [0:0] icmp_ln578_fu_258_p2;
wire   [0:0] xor_ln584_1_fu_252_p2;
wire   [0:0] and_ln578_1_fu_281_p2;
wire   [0:0] and_ln578_fu_276_p2;
wire   [0:0] and_ln578_2_fu_287_p2;
wire   [0:0] and_ln589_fu_299_p2;
wire   [0:0] icmp_ln590_fu_293_p2;
wire   [0:0] icmp_ln590_1_fu_311_p2;
wire   [0:0] and_ln590_1_fu_317_p2;
wire   [0:0] xor_ln591_fu_323_p2;
wire   [0:0] icmp_ln590_2_fu_335_p2;
wire   [0:0] and_ln590_2_fu_341_p2;
wire   [0:0] and_ln595_fu_347_p2;
wire   [0:0] and_ln595_1_fu_353_p2;
wire   [0:0] xor_ln593_fu_264_p2;
wire   [0:0] and_ln596_fu_359_p2;
wire   [0:0] icmp_ln597_fu_270_p2;
wire   [0:0] and_ln591_fu_329_p2;
wire   [0:0] and_ln590_fu_305_p2;
wire   [0:0] or_ln596_fu_373_p2;
wire   [0:0] select_ln596_fu_365_p3;
wire   [0:0] select_ln596_1_fu_379_p3;
wire   [0:0] xor_ln589_fu_395_p2;
wire   [0:0] xor_ln595_fu_413_p2;
wire   [0:0] xor_ln595_1_fu_425_p2;
wire   [0:0] and_ln591_1_fu_407_p2;
wire   [0:0] or_ln589_fu_401_p2;
wire   [0:0] xor_ln596_fu_443_p2;
wire   [0:0] select_ln596_2_fu_387_p3;
wire   [0:0] and_ln596_1_fu_437_p2;
wire   [0:0] or_ln595_1_fu_431_p2;
wire   [0:0] xor_ln596_1_fu_455_p2;
wire   [0:0] or_ln595_fu_419_p2;
wire   [0:0] and_ln596_3_fu_461_p2;
wire   [0:0] and_ln596_2_fu_449_p2;
wire   [0:0] and_ln596_4_fu_467_p2;
reg   [0:0] ap_return_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_return_preg <= and_ln596_4_fu_467_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln577_reg_473 <= icmp_ln577_fu_204_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_return = and_ln596_4_fu_467_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_busy_ce0 = 1'b1;
    end else begin
        state_rob_entries_busy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_is_load_ce0 = 1'b1;
    end else begin
        state_rob_entries_is_load_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_completed_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_completed_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_request_sent_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_request_sent_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_transaction_id_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_transaction_id_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_memory_valid_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_uop_queue_rob_allocation_id_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_queue_rob_allocation_id_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        state_rob_entries_valid_ce0 = 1'b1;
    end else begin
        state_rob_entries_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln578_1_fu_281_p2 = (xor_ln584_1_fu_252_p2 & icmp_ln578_fu_258_p2);

assign and_ln578_2_fu_287_p2 = (and_ln578_fu_276_p2 & and_ln578_1_fu_281_p2);

assign and_ln578_fu_276_p2 = (state_rob_entries_valid_q0 & icmp_ln577_reg_473);

assign and_ln589_fu_299_p2 = (state_rob_entries_busy_q0 & and_ln578_2_fu_287_p2);

assign and_ln590_1_fu_317_p2 = (icmp_ln590_1_fu_311_p2 & and_ln589_fu_299_p2);

assign and_ln590_2_fu_341_p2 = (icmp_ln590_2_fu_335_p2 & and_ln589_fu_299_p2);

assign and_ln590_fu_305_p2 = (icmp_ln590_fu_293_p2 & and_ln589_fu_299_p2);

assign and_ln591_1_fu_407_p2 = (state_rob_entries_memory_valid_q0 & and_ln590_1_fu_317_p2);

assign and_ln591_fu_329_p2 = (xor_ln591_fu_323_p2 & and_ln590_1_fu_317_p2);

assign and_ln595_1_fu_353_p2 = (state_rob_entries_memory_request_sent_q0 & and_ln595_fu_347_p2);

assign and_ln595_fu_347_p2 = (state_rob_entries_is_load_q0 & and_ln590_2_fu_341_p2);

assign and_ln596_1_fu_437_p2 = (state_rob_entries_memory_completed_q0 & and_ln595_1_fu_353_p2);

assign and_ln596_2_fu_449_p2 = (xor_ln596_fu_443_p2 & select_ln596_2_fu_387_p3);

assign and_ln596_3_fu_461_p2 = (xor_ln596_1_fu_455_p2 & or_ln595_fu_419_p2);

assign and_ln596_4_fu_467_p2 = (and_ln596_3_fu_461_p2 & and_ln596_2_fu_449_p2);

assign and_ln596_fu_359_p2 = (xor_ln593_fu_264_p2 & and_ln595_1_fu_353_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign icmp_ln577_fu_204_p2 = ((tmp_fu_194_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln578_fu_258_p2 = ((state_rob_entries_uop_queue_rob_allocation_id_q0 == p_read4) ? 1'b1 : 1'b0);

assign icmp_ln584_fu_228_p2 = ((p_read1 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln585_fu_234_p2 = ((p_read2 > 8'd2) ? 1'b1 : 1'b0);

assign icmp_ln590_1_fu_311_p2 = ((p_read1 == 8'd2) ? 1'b1 : 1'b0);

assign icmp_ln590_2_fu_335_p2 = ((p_read1 == 8'd4) ? 1'b1 : 1'b0);

assign icmp_ln590_fu_293_p2 = ((p_read1 == 8'd3) ? 1'b1 : 1'b0);

assign icmp_ln597_fu_270_p2 = ((state_rob_entries_memory_transaction_id_q0 == p_read5) ? 1'b1 : 1'b0);

assign or_ln577_1_fu_240_p2 = (xor_ln584_fu_222_p2 | icmp_ln585_fu_234_p2);

assign or_ln577_fu_246_p2 = (or_ln577_1_fu_240_p2 | icmp_ln584_fu_228_p2);

assign or_ln589_fu_401_p2 = (xor_ln589_fu_395_p2 | state_rob_entries_busy_q0);

assign or_ln595_1_fu_431_p2 = (xor_ln595_1_fu_425_p2 | state_rob_entries_memory_request_sent_q0);

assign or_ln595_fu_419_p2 = (xor_ln595_fu_413_p2 | state_rob_entries_is_load_q0);

assign or_ln596_fu_373_p2 = (and_ln596_fu_359_p2 | and_ln591_fu_329_p2);

assign select_ln596_1_fu_379_p3 = ((and_ln590_fu_305_p2[0:0] == 1'b1) ? xor_ln593_fu_264_p2 : and_ln578_2_fu_287_p2);

assign select_ln596_2_fu_387_p3 = ((or_ln596_fu_373_p2[0:0] == 1'b1) ? select_ln596_fu_365_p3 : select_ln596_1_fu_379_p3);

assign select_ln596_fu_365_p3 = ((and_ln596_fu_359_p2[0:0] == 1'b1) ? icmp_ln597_fu_270_p2 : xor_ln593_fu_264_p2);

assign state_rob_entries_busy_address0 = zext_ln577_fu_210_p1;

assign state_rob_entries_is_load_address0 = zext_ln577_fu_210_p1;

assign state_rob_entries_memory_completed_address0 = zext_ln577_fu_210_p1;

assign state_rob_entries_memory_request_sent_address0 = zext_ln577_fu_210_p1;

assign state_rob_entries_memory_transaction_id_address0 = zext_ln577_fu_210_p1;

assign state_rob_entries_memory_valid_address0 = zext_ln577_fu_210_p1;

assign state_rob_entries_uop_queue_rob_allocation_id_address0 = zext_ln577_fu_210_p1;

assign state_rob_entries_valid_address0 = zext_ln577_fu_210_p1;

assign tmp_fu_194_p4 = {{p_read3[7:5]}};

assign xor_ln584_1_fu_252_p2 = (or_ln577_fu_246_p2 ^ 1'd1);

assign xor_ln584_fu_222_p2 = (p_read ^ 1'd1);

assign xor_ln589_fu_395_p2 = (1'd1 ^ and_ln578_2_fu_287_p2);

assign xor_ln591_fu_323_p2 = (state_rob_entries_memory_valid_q0 ^ 1'd1);

assign xor_ln593_fu_264_p2 = (state_rob_entries_memory_completed_q0 ^ 1'd1);

assign xor_ln595_1_fu_425_p2 = (1'd1 ^ and_ln595_fu_347_p2);

assign xor_ln595_fu_413_p2 = (1'd1 ^ and_ln590_2_fu_341_p2);

assign xor_ln596_1_fu_455_p2 = (or_ln595_1_fu_431_p2 ^ and_ln596_1_fu_437_p2);

assign xor_ln596_fu_443_p2 = (or_ln589_fu_401_p2 ^ and_ln591_1_fu_407_p2);

assign zext_ln577_fu_210_p1 = p_read3;

endmodule //boom_core_top_completion_is_valid
