// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module boom_core_top_apply_writeback_ports (
        ap_start,
        ap_ready,
        state_completion_writebacks_valid_0,
        state_completion_writebacks_valid_1,
        state_completion_writebacks_pdst_0,
        state_completion_writebacks_pdst_1,
        state_int_rf_latest_bank_i,
        state_int_rf_latest_bank_o,
        state_int_rf_latest_bank_o_ap_vld,
        state_completion_duplicate_writebacks_i,
        state_completion_duplicate_writebacks_o,
        state_completion_duplicate_writebacks_o_ap_vld,
        state_completion_dropped_writebacks_i,
        state_completion_dropped_writebacks_o,
        state_completion_dropped_writebacks_o_ap_vld,
        state_completion_writebacks_value_0,
        state_int_rf_bank0_address0,
        state_int_rf_bank0_ce0,
        state_int_rf_bank0_we0,
        state_int_rf_bank0_d0,
        state_completion_writebacks_value_1,
        state_int_rf_bank1_address0,
        state_int_rf_bank1_ce0,
        state_int_rf_bank1_we0,
        state_int_rf_bank1_d0
);


input   ap_start;
output   ap_ready;
input  [0:0] state_completion_writebacks_valid_0;
input  [0:0] state_completion_writebacks_valid_1;
input  [7:0] state_completion_writebacks_pdst_0;
input  [7:0] state_completion_writebacks_pdst_1;
input  [63:0] state_int_rf_latest_bank_i;
output  [63:0] state_int_rf_latest_bank_o;
output   state_int_rf_latest_bank_o_ap_vld;
input  [63:0] state_completion_duplicate_writebacks_i;
output  [63:0] state_completion_duplicate_writebacks_o;
output   state_completion_duplicate_writebacks_o_ap_vld;
input  [63:0] state_completion_dropped_writebacks_i;
output  [63:0] state_completion_dropped_writebacks_o;
output   state_completion_dropped_writebacks_o_ap_vld;
input  [63:0] state_completion_writebacks_value_0;
output  [5:0] state_int_rf_bank0_address0;
output   state_int_rf_bank0_ce0;
output   state_int_rf_bank0_we0;
output  [63:0] state_int_rf_bank0_d0;
input  [63:0] state_completion_writebacks_value_1;
output  [5:0] state_int_rf_bank1_address0;
output   state_int_rf_bank1_ce0;
output   state_int_rf_bank1_we0;
output  [63:0] state_int_rf_bank1_d0;

reg[63:0] state_int_rf_latest_bank_o;
reg state_int_rf_latest_bank_o_ap_vld;
reg[63:0] state_completion_duplicate_writebacks_o;
reg state_completion_duplicate_writebacks_o_ap_vld;
reg[63:0] state_completion_dropped_writebacks_o;
reg state_completion_dropped_writebacks_o_ap_vld;
reg state_int_rf_bank0_ce0;
reg state_int_rf_bank0_we0;
reg state_int_rf_bank1_ce0;
reg state_int_rf_bank1_we0;

wire   [63:0] latest_3_fu_147_p2;
reg   [63:0] ap_phi_mux_latest_2_phi_fu_67_p4;
wire   [0:0] and_ln1060_fu_119_p2;
wire   [0:0] state_completion_writebacks_valid_0_load_load_fu_85_p1;
wire   [63:0] latest_4_fu_170_p2;
reg   [63:0] ap_phi_mux_latest_1_phi_fu_76_p6;
wire   [0:0] state_completion_writebacks_valid_1_load_load_fu_89_p1;
wire   [63:0] zext_ln1067_fu_130_p1;
wire   [63:0] zext_ln1072_fu_159_p1;
wire   [63:0] add_ln1061_fu_181_p2;
wire   [63:0] add_ln1062_fu_197_p2;
wire   [0:0] icmp_ln1059_fu_107_p2;
wire   [0:0] and_ln1060_1_fu_113_p2;
wire   [63:0] shl_ln1068_fu_135_p2;
wire   [63:0] xor_ln1068_fu_141_p2;
wire   [63:0] shl_ln1073_fu_164_p2;
wire    ap_ce_reg;

always @ (*) begin
    if (((state_completion_writebacks_valid_1_load_load_fu_89_p1 == 1'd0) & (1'd0 == and_ln1060_fu_119_p2))) begin
        ap_phi_mux_latest_1_phi_fu_76_p6 = ap_phi_mux_latest_2_phi_fu_67_p4;
    end else if ((1'd1 == and_ln1060_fu_119_p2)) begin
        ap_phi_mux_latest_1_phi_fu_76_p6 = state_int_rf_latest_bank_i;
    end else if (((state_completion_writebacks_valid_1_load_load_fu_89_p1 == 1'd1) & (1'd0 == and_ln1060_fu_119_p2))) begin
        ap_phi_mux_latest_1_phi_fu_76_p6 = latest_4_fu_170_p2;
    end else begin
        ap_phi_mux_latest_1_phi_fu_76_p6 = 'bx;
    end
end

always @ (*) begin
    if ((1'd0 == and_ln1060_fu_119_p2)) begin
        if ((state_completion_writebacks_valid_0_load_load_fu_85_p1 == 1'd0)) begin
            ap_phi_mux_latest_2_phi_fu_67_p4 = state_int_rf_latest_bank_i;
        end else if ((state_completion_writebacks_valid_0_load_load_fu_85_p1 == 1'd1)) begin
            ap_phi_mux_latest_2_phi_fu_67_p4 = latest_3_fu_147_p2;
        end else begin
            ap_phi_mux_latest_2_phi_fu_67_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_latest_2_phi_fu_67_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'd1 == and_ln1060_fu_119_p2)) begin
        state_completion_dropped_writebacks_o = add_ln1062_fu_197_p2;
    end else begin
        state_completion_dropped_writebacks_o = state_completion_dropped_writebacks_i;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln1060_fu_119_p2) & (ap_start == 1'b1))) begin
        state_completion_dropped_writebacks_o_ap_vld = 1'b1;
    end else begin
        state_completion_dropped_writebacks_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'd1 == and_ln1060_fu_119_p2)) begin
        state_completion_duplicate_writebacks_o = add_ln1061_fu_181_p2;
    end else begin
        state_completion_duplicate_writebacks_o = state_completion_duplicate_writebacks_i;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln1060_fu_119_p2) & (ap_start == 1'b1))) begin
        state_completion_duplicate_writebacks_o_ap_vld = 1'b1;
    end else begin
        state_completion_duplicate_writebacks_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        state_int_rf_bank0_ce0 = 1'b1;
    end else begin
        state_int_rf_bank0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((state_completion_writebacks_valid_0_load_load_fu_85_p1 == 1'd1) & (1'd0 == and_ln1060_fu_119_p2) & (ap_start == 1'b1))) begin
        state_int_rf_bank0_we0 = 1'b1;
    end else begin
        state_int_rf_bank0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        state_int_rf_bank1_ce0 = 1'b1;
    end else begin
        state_int_rf_bank1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((state_completion_writebacks_valid_1_load_load_fu_89_p1 == 1'd1) & (1'd0 == and_ln1060_fu_119_p2) & (ap_start == 1'b1))) begin
        state_int_rf_bank1_we0 = 1'b1;
    end else begin
        state_int_rf_bank1_we0 = 1'b0;
    end
end

always @ (*) begin
    state_int_rf_latest_bank_o = ap_phi_mux_latest_1_phi_fu_76_p6;
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        state_int_rf_latest_bank_o_ap_vld = 1'b1;
    end else begin
        state_int_rf_latest_bank_o_ap_vld = 1'b0;
    end
end

assign add_ln1061_fu_181_p2 = (state_completion_duplicate_writebacks_i + 64'd1);

assign add_ln1062_fu_197_p2 = (state_completion_dropped_writebacks_i + 64'd2);

assign and_ln1060_1_fu_113_p2 = (state_completion_writebacks_valid_1 & icmp_ln1059_fu_107_p2);

assign and_ln1060_fu_119_p2 = (state_completion_writebacks_valid_0 & and_ln1060_1_fu_113_p2);

assign ap_ready = ap_start;

assign icmp_ln1059_fu_107_p2 = ((state_completion_writebacks_pdst_0 == state_completion_writebacks_pdst_1) ? 1'b1 : 1'b0);

assign latest_3_fu_147_p2 = (xor_ln1068_fu_141_p2 & state_int_rf_latest_bank_i);

assign latest_4_fu_170_p2 = (shl_ln1073_fu_164_p2 | ap_phi_mux_latest_2_phi_fu_67_p4);

assign shl_ln1068_fu_135_p2 = 64'd1 << zext_ln1067_fu_130_p1;

assign shl_ln1073_fu_164_p2 = 64'd1 << zext_ln1072_fu_159_p1;

assign state_completion_writebacks_valid_0_load_load_fu_85_p1 = state_completion_writebacks_valid_0;

assign state_completion_writebacks_valid_1_load_load_fu_89_p1 = state_completion_writebacks_valid_1;

assign state_int_rf_bank0_address0 = zext_ln1067_fu_130_p1;

assign state_int_rf_bank0_d0 = state_completion_writebacks_value_0;

assign state_int_rf_bank1_address0 = zext_ln1072_fu_159_p1;

assign state_int_rf_bank1_d0 = state_completion_writebacks_value_1;

assign xor_ln1068_fu_141_p2 = (shl_ln1068_fu_135_p2 ^ 64'd18446744073709551615);

assign zext_ln1067_fu_130_p1 = state_completion_writebacks_pdst_0;

assign zext_ln1072_fu_159_p1 = state_completion_writebacks_pdst_1;

endmodule //boom_core_top_apply_writeback_ports
