// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module boom_core_top_rob_commit_module (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pipe_2_din,
        pipe_2_full_n,
        pipe_2_write,
        pipe_4_din,
        pipe_4_full_n,
        pipe_4_write,
        state_execute_alu_results_valid_0,
        state_execute_alu_results_memory_valid_0,
        state_execute_alu_results_is_load_0,
        state_execute_alu_results_is_store_0,
        state_execute_alu_results_uop_ctrl_is_load_0,
        state_execute_alu_results_uop_ctrl_is_sta_0,
        state_execute_alu_results_uop_queue_rob_idx_0,
        state_rob_entries_valid_address0,
        state_rob_entries_valid_ce0,
        state_rob_entries_valid_we0,
        state_rob_entries_valid_d0,
        state_rob_entries_valid_q0,
        state_rob_entries_busy_address0,
        state_rob_entries_busy_ce0,
        state_rob_entries_busy_we0,
        state_rob_entries_busy_d0,
        state_rob_entries_busy_q0,
        state_execute_alu_results_exception_0,
        state_rob_entries_exception_address0,
        state_rob_entries_exception_ce0,
        state_rob_entries_exception_we0,
        state_rob_entries_exception_d0,
        state_rob_entries_exception_q0,
        state_rob_head_i,
        state_rob_head_o,
        state_rob_head_o_ap_vld,
        state_rob_tail,
        state_rob_maybe_full_i,
        state_rob_maybe_full_o,
        state_rob_maybe_full_o_ap_vld,
        state_rob_entries_uop_uopc_address0,
        state_rob_entries_uop_uopc_ce0,
        state_rob_entries_uop_uopc_q0,
        state_int_rf_address0,
        state_int_rf_ce0,
        state_int_rf_q0,
        state_rob_state,
        state_rob_state_ap_vld,
        state_rob_entries_uop_ctrl_is_load_address0,
        state_rob_entries_uop_ctrl_is_load_ce0,
        state_rob_entries_uop_ctrl_is_load_q0,
        state_rob_entries_is_load_address0,
        state_rob_entries_is_load_ce0,
        state_rob_entries_is_load_q0,
        state_rob_entries_memory_completed_address0,
        state_rob_entries_memory_completed_ce0,
        state_rob_entries_memory_completed_we0,
        state_rob_entries_memory_completed_d0,
        state_rob_entries_memory_completed_q0,
        state_rob_entries_uop_ctrl_is_sta_address0,
        state_rob_entries_uop_ctrl_is_sta_ce0,
        state_rob_entries_uop_ctrl_is_sta_q0,
        state_rob_entries_is_store_address0,
        state_rob_entries_is_store_ce0,
        state_rob_entries_is_store_q0,
        state_rob_entries_memory_valid_address0,
        state_rob_entries_memory_valid_ce0,
        state_rob_entries_memory_valid_q0,
        state_rob_entries_memory_request_sent_address0,
        state_rob_entries_memory_request_sent_ce0,
        state_rob_entries_memory_request_sent_we0,
        state_rob_entries_memory_request_sent_d0,
        state_rob_entries_memory_request_sent_q0,
        state_lsu_next_transaction_id_i,
        state_lsu_next_transaction_id_o,
        state_lsu_next_transaction_id_o_ap_vld,
        state_rob_entries_uop_queue_rob_idx_address0,
        state_rob_entries_uop_queue_rob_idx_ce0,
        state_rob_entries_uop_queue_rob_idx_q0,
        state_rob_entries_memory_address_address0,
        state_rob_entries_memory_address_ce0,
        state_rob_entries_memory_address_q0,
        state_rob_entries_memory_data_address0,
        state_rob_entries_memory_data_ce0,
        state_rob_entries_memory_data_q0,
        state_rob_entries_memory_size_address0,
        state_rob_entries_memory_size_ce0,
        state_rob_entries_memory_size_q0,
        state_rob_entries_memory_mask_address0,
        state_rob_entries_memory_mask_ce0,
        state_rob_entries_memory_mask_q0,
        state_rob_entries_uop_branch_br_mask_address0,
        state_rob_entries_uop_branch_br_mask_ce0,
        state_rob_entries_uop_branch_br_mask_q0,
        state_csr_instret_i,
        state_csr_instret_o,
        state_csr_instret_o_ap_vld,
        state_rob_entries_uop_debug_pc_address0,
        state_rob_entries_uop_debug_pc_ce0,
        state_rob_entries_uop_debug_pc_q0,
        state_rob_entries_uop_inst_address0,
        state_rob_entries_uop_inst_ce0,
        state_rob_entries_uop_inst_q0,
        state_rob_entries_uop_rename_dst_rtype_address0,
        state_rob_entries_uop_rename_dst_rtype_ce0,
        state_rob_entries_uop_rename_dst_rtype_q0,
        state_rob_entries_uop_rename_pdst_address0,
        state_rob_entries_uop_rename_pdst_ce0,
        state_rob_entries_uop_rename_pdst_q0,
        state_rob_entries_uop_rename_ldst_address0,
        state_rob_entries_uop_rename_ldst_ce0,
        state_rob_entries_uop_rename_ldst_q0,
        state_rename_int_map_table_committed_map_table_address0,
        state_rename_int_map_table_committed_map_table_ce0,
        state_rename_int_map_table_committed_map_table_we0,
        state_rename_int_map_table_committed_map_table_d0,
        state_rob_entries_uop_rename_stale_pdst_address0,
        state_rob_entries_uop_rename_stale_pdst_ce0,
        state_rob_entries_uop_rename_stale_pdst_q0,
        state_rename_int_free_list_head,
        state_rename_int_free_list_count_i,
        state_rename_int_free_list_count_o,
        state_rename_int_free_list_count_o_ap_vld,
        state_rename_int_free_list_free_list_address0,
        state_rename_int_free_list_free_list_ce0,
        state_rename_int_free_list_free_list_we0,
        state_rename_int_free_list_free_list_d0,
        state_rename_int_free_list_free_list_q0,
        state_rename_int_free_list_busy_table_address0,
        state_rename_int_free_list_busy_table_ce0,
        state_rename_int_free_list_busy_table_we0,
        state_rename_int_free_list_busy_table_d0,
        state_rename_int_free_list_tail_i,
        state_rename_int_free_list_tail_o,
        state_rename_int_free_list_tail_o_ap_vld,
        state_rename_int_map_table_map_table_address0,
        state_rename_int_map_table_map_table_ce0,
        state_rename_int_map_table_map_table_q0
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [282:0] pipe_2_din;
input   pipe_2_full_n;
output   pipe_2_write;
output  [517:0] pipe_4_din;
input   pipe_4_full_n;
output   pipe_4_write;
input  [0:0] state_execute_alu_results_valid_0;
input  [0:0] state_execute_alu_results_memory_valid_0;
input  [0:0] state_execute_alu_results_is_load_0;
input  [0:0] state_execute_alu_results_is_store_0;
input  [0:0] state_execute_alu_results_uop_ctrl_is_load_0;
input  [0:0] state_execute_alu_results_uop_ctrl_is_sta_0;
input  [7:0] state_execute_alu_results_uop_queue_rob_idx_0;
output  [4:0] state_rob_entries_valid_address0;
output   state_rob_entries_valid_ce0;
output   state_rob_entries_valid_we0;
output  [0:0] state_rob_entries_valid_d0;
input  [0:0] state_rob_entries_valid_q0;
output  [4:0] state_rob_entries_busy_address0;
output   state_rob_entries_busy_ce0;
output   state_rob_entries_busy_we0;
output  [0:0] state_rob_entries_busy_d0;
input  [0:0] state_rob_entries_busy_q0;
input  [0:0] state_execute_alu_results_exception_0;
output  [4:0] state_rob_entries_exception_address0;
output   state_rob_entries_exception_ce0;
output   state_rob_entries_exception_we0;
output  [0:0] state_rob_entries_exception_d0;
input  [0:0] state_rob_entries_exception_q0;
input  [4:0] state_rob_head_i;
output  [4:0] state_rob_head_o;
output   state_rob_head_o_ap_vld;
input  [4:0] state_rob_tail;
input  [0:0] state_rob_maybe_full_i;
output  [0:0] state_rob_maybe_full_o;
output   state_rob_maybe_full_o_ap_vld;
output  [4:0] state_rob_entries_uop_uopc_address0;
output   state_rob_entries_uop_uopc_ce0;
input  [7:0] state_rob_entries_uop_uopc_q0;
output  [5:0] state_int_rf_address0;
output   state_int_rf_ce0;
input  [63:0] state_int_rf_q0;
output  [1:0] state_rob_state;
output   state_rob_state_ap_vld;
output  [4:0] state_rob_entries_uop_ctrl_is_load_address0;
output   state_rob_entries_uop_ctrl_is_load_ce0;
input  [0:0] state_rob_entries_uop_ctrl_is_load_q0;
output  [4:0] state_rob_entries_is_load_address0;
output   state_rob_entries_is_load_ce0;
input  [0:0] state_rob_entries_is_load_q0;
output  [4:0] state_rob_entries_memory_completed_address0;
output   state_rob_entries_memory_completed_ce0;
output   state_rob_entries_memory_completed_we0;
output  [0:0] state_rob_entries_memory_completed_d0;
input  [0:0] state_rob_entries_memory_completed_q0;
output  [4:0] state_rob_entries_uop_ctrl_is_sta_address0;
output   state_rob_entries_uop_ctrl_is_sta_ce0;
input  [0:0] state_rob_entries_uop_ctrl_is_sta_q0;
output  [4:0] state_rob_entries_is_store_address0;
output   state_rob_entries_is_store_ce0;
input  [0:0] state_rob_entries_is_store_q0;
output  [4:0] state_rob_entries_memory_valid_address0;
output   state_rob_entries_memory_valid_ce0;
input  [0:0] state_rob_entries_memory_valid_q0;
output  [4:0] state_rob_entries_memory_request_sent_address0;
output   state_rob_entries_memory_request_sent_ce0;
output   state_rob_entries_memory_request_sent_we0;
output  [0:0] state_rob_entries_memory_request_sent_d0;
input  [0:0] state_rob_entries_memory_request_sent_q0;
input  [31:0] state_lsu_next_transaction_id_i;
output  [31:0] state_lsu_next_transaction_id_o;
output   state_lsu_next_transaction_id_o_ap_vld;
output  [4:0] state_rob_entries_uop_queue_rob_idx_address0;
output   state_rob_entries_uop_queue_rob_idx_ce0;
input  [4:0] state_rob_entries_uop_queue_rob_idx_q0;
output  [4:0] state_rob_entries_memory_address_address0;
output   state_rob_entries_memory_address_ce0;
input  [63:0] state_rob_entries_memory_address_q0;
output  [4:0] state_rob_entries_memory_data_address0;
output   state_rob_entries_memory_data_ce0;
input  [63:0] state_rob_entries_memory_data_q0;
output  [4:0] state_rob_entries_memory_size_address0;
output   state_rob_entries_memory_size_ce0;
input  [7:0] state_rob_entries_memory_size_q0;
output  [4:0] state_rob_entries_memory_mask_address0;
output   state_rob_entries_memory_mask_ce0;
input  [4:0] state_rob_entries_memory_mask_q0;
output  [4:0] state_rob_entries_uop_branch_br_mask_address0;
output   state_rob_entries_uop_branch_br_mask_ce0;
input  [7:0] state_rob_entries_uop_branch_br_mask_q0;
input  [63:0] state_csr_instret_i;
output  [63:0] state_csr_instret_o;
output   state_csr_instret_o_ap_vld;
output  [4:0] state_rob_entries_uop_debug_pc_address0;
output   state_rob_entries_uop_debug_pc_ce0;
input  [63:0] state_rob_entries_uop_debug_pc_q0;
output  [4:0] state_rob_entries_uop_inst_address0;
output   state_rob_entries_uop_inst_ce0;
input  [31:0] state_rob_entries_uop_inst_q0;
output  [4:0] state_rob_entries_uop_rename_dst_rtype_address0;
output   state_rob_entries_uop_rename_dst_rtype_ce0;
input  [1:0] state_rob_entries_uop_rename_dst_rtype_q0;
output  [4:0] state_rob_entries_uop_rename_pdst_address0;
output   state_rob_entries_uop_rename_pdst_ce0;
input  [7:0] state_rob_entries_uop_rename_pdst_q0;
output  [4:0] state_rob_entries_uop_rename_ldst_address0;
output   state_rob_entries_uop_rename_ldst_ce0;
input  [4:0] state_rob_entries_uop_rename_ldst_q0;
output  [4:0] state_rename_int_map_table_committed_map_table_address0;
output   state_rename_int_map_table_committed_map_table_ce0;
output   state_rename_int_map_table_committed_map_table_we0;
output  [7:0] state_rename_int_map_table_committed_map_table_d0;
output  [4:0] state_rob_entries_uop_rename_stale_pdst_address0;
output   state_rob_entries_uop_rename_stale_pdst_ce0;
input  [7:0] state_rob_entries_uop_rename_stale_pdst_q0;
input  [5:0] state_rename_int_free_list_head;
input  [7:0] state_rename_int_free_list_count_i;
output  [7:0] state_rename_int_free_list_count_o;
output   state_rename_int_free_list_count_o_ap_vld;
output  [5:0] state_rename_int_free_list_free_list_address0;
output   state_rename_int_free_list_free_list_ce0;
output   state_rename_int_free_list_free_list_we0;
output  [7:0] state_rename_int_free_list_free_list_d0;
input  [7:0] state_rename_int_free_list_free_list_q0;
output  [5:0] state_rename_int_free_list_busy_table_address0;
output   state_rename_int_free_list_busy_table_ce0;
output   state_rename_int_free_list_busy_table_we0;
output  [0:0] state_rename_int_free_list_busy_table_d0;
input  [5:0] state_rename_int_free_list_tail_i;
output  [5:0] state_rename_int_free_list_tail_o;
output   state_rename_int_free_list_tail_o_ap_vld;
output  [4:0] state_rename_int_map_table_map_table_address0;
output   state_rename_int_map_table_map_table_ce0;
input  [7:0] state_rename_int_map_table_map_table_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg pipe_2_write;
reg pipe_4_write;
reg[4:0] state_rob_entries_valid_address0;
reg state_rob_entries_valid_ce0;
reg state_rob_entries_valid_we0;
reg[4:0] state_rob_entries_busy_address0;
reg state_rob_entries_busy_ce0;
reg state_rob_entries_busy_we0;
reg[4:0] state_rob_entries_exception_address0;
reg state_rob_entries_exception_ce0;
reg state_rob_entries_exception_we0;
reg[4:0] state_rob_head_o;
reg state_rob_head_o_ap_vld;
reg[0:0] state_rob_maybe_full_o;
reg state_rob_maybe_full_o_ap_vld;
reg state_rob_entries_uop_uopc_ce0;
reg[5:0] state_int_rf_address0;
reg state_int_rf_ce0;
reg state_rob_state_ap_vld;
reg state_rob_entries_uop_ctrl_is_load_ce0;
reg state_rob_entries_is_load_ce0;
reg[4:0] state_rob_entries_memory_completed_address0;
reg state_rob_entries_memory_completed_ce0;
reg state_rob_entries_memory_completed_we0;
reg state_rob_entries_uop_ctrl_is_sta_ce0;
reg[4:0] state_rob_entries_is_store_address0;
reg state_rob_entries_is_store_ce0;
reg[4:0] state_rob_entries_memory_valid_address0;
reg state_rob_entries_memory_valid_ce0;
reg[4:0] state_rob_entries_memory_request_sent_address0;
reg state_rob_entries_memory_request_sent_ce0;
reg state_rob_entries_memory_request_sent_we0;
reg[31:0] state_lsu_next_transaction_id_o;
reg state_lsu_next_transaction_id_o_ap_vld;
reg state_rob_entries_uop_queue_rob_idx_ce0;
reg[4:0] state_rob_entries_memory_address_address0;
reg state_rob_entries_memory_address_ce0;
reg[4:0] state_rob_entries_memory_data_address0;
reg state_rob_entries_memory_data_ce0;
reg state_rob_entries_memory_size_ce0;
reg[4:0] state_rob_entries_memory_mask_address0;
reg state_rob_entries_memory_mask_ce0;
reg state_rob_entries_uop_branch_br_mask_ce0;
reg[63:0] state_csr_instret_o;
reg state_csr_instret_o_ap_vld;
reg state_rob_entries_uop_debug_pc_ce0;
reg state_rob_entries_uop_inst_ce0;
reg state_rob_entries_uop_rename_dst_rtype_ce0;
reg state_rob_entries_uop_rename_pdst_ce0;
reg state_rob_entries_uop_rename_ldst_ce0;
reg state_rename_int_map_table_committed_map_table_ce0;
reg state_rename_int_map_table_committed_map_table_we0;
reg state_rob_entries_uop_rename_stale_pdst_ce0;
reg[7:0] state_rename_int_free_list_count_o;
reg state_rename_int_free_list_count_o_ap_vld;
reg[5:0] state_rename_int_free_list_free_list_address0;
reg state_rename_int_free_list_free_list_ce0;
reg state_rename_int_free_list_free_list_we0;
reg state_rename_int_free_list_busy_table_ce0;
reg state_rename_int_free_list_busy_table_we0;
reg[5:0] state_rename_int_free_list_tail_o;
reg state_rename_int_free_list_tail_o_ap_vld;
reg state_rename_int_map_table_map_table_ce0;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    pipe_2_blk_n;
wire    ap_CS_fsm_state13;
reg   [0:0] state_rob_entries_is_store_load_reg_1337;
reg   [0:0] state_rob_entries_memory_request_sent_load_reg_1354;
reg   [0:0] state_rob_entries_uop_ctrl_is_sta_load_reg_1328;
reg    pipe_4_blk_n;
wire    ap_CS_fsm_state18;
reg   [0:0] state_rob_entries_exception_load_reg_1288;
wire   [0:0] icmp_ln1134_fu_1037_p2;
wire   [0:0] tmp_7_nbwritereq_fu_203_p3;
reg   [0:0] and_ln1133_reg_1552;
reg   [0:0] and_ln1211_reg_1521;
reg   [0:0] icmp_ln1209_reg_1462;
wire   [0:0] state_execute_alu_results_valid_0_load_load_fu_674_p1;
wire   [0:0] state_execute_alu_results_memory_valid_0_load_load_fu_678_p1;
wire   [0:0] state_execute_alu_results_is_load_0_load_load_fu_682_p1;
wire   [0:0] state_execute_alu_results_is_store_0_load_load_fu_686_p1;
wire   [0:0] state_execute_alu_results_uop_ctrl_is_load_0_load_load_fu_690_p1;
wire   [0:0] state_execute_alu_results_uop_ctrl_is_sta_0_load_load_fu_694_p1;
wire   [0:0] icmp_ln477_fu_712_p2;
reg   [0:0] icmp_ln477_reg_1206;
wire   [63:0] zext_ln477_fu_718_p1;
reg   [63:0] zext_ln477_reg_1210;
reg   [4:0] state_rob_head_load_reg_1227;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln1158_fu_751_p1;
reg   [63:0] zext_ln1158_reg_1235;
wire   [0:0] or_ln1157_fu_745_p2;
reg   [4:0] state_rob_entries_valid_addr_2_reg_1267;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [0:0] state_rob_entries_uop_ctrl_is_load_load_reg_1302;
wire    ap_CS_fsm_state6;
reg   [0:0] state_rob_entries_is_load_load_reg_1311;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [4:0] state_rob_entries_memory_request_sent_addr_reg_1349;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire   [0:0] tmp_nbwritereq_fu_188_p3;
wire    ap_CS_fsm_state14;
reg   [7:0] state_rob_entries_uop_rename_pdst_load_reg_1411;
wire   [4:0] state_rob_entries_memory_valid_addr_1_gep_fu_553_p3;
wire   [4:0] state_rob_entries_is_store_addr_1_gep_fu_561_p3;
wire   [4:0] state_rob_entries_memory_address_addr_1_gep_fu_569_p3;
wire   [4:0] state_rob_entries_memory_data_addr_1_gep_fu_577_p3;
wire   [4:0] state_rob_entries_memory_mask_addr_1_gep_fu_585_p3;
reg   [63:0] ce_pc_reg_1452;
wire    ap_CS_fsm_state15;
reg   [31:0] ce_inst_reg_1457;
wire   [0:0] icmp_ln1209_fu_862_p2;
wire   [0:0] ce_rd_valid_fu_867_p2;
reg   [0:0] ce_rd_valid_reg_1466;
reg   [4:0] ce_rd_reg_1471;
wire   [63:0] ce_rd_value_fu_873_p3;
reg   [63:0] ce_rd_value_reg_1476;
reg   [0:0] ce_memory_valid_reg_1481;
reg   [0:0] ce_is_store_reg_1486;
reg   [63:0] ce_memory_address_reg_1491;
reg   [63:0] ce_memory_data_reg_1497;
reg   [4:0] ce_memory_mask_reg_1503;
reg   [7:0] preg_reg_1514;
wire    ap_CS_fsm_state16;
wire   [0:0] and_ln1211_fu_898_p2;
wire   [5:0] empty_fu_912_p1;
reg   [5:0] empty_reg_1542;
wire   [31:0] conv_i_i_fu_916_p1;
reg   [31:0] conv_i_i_reg_1547;
wire   [0:0] and_ln1133_fu_944_p2;
wire    ap_CS_fsm_state17;
wire   [31:0] i_4_fu_950_p2;
reg   [31:0] i_4_reg_1556;
wire   [0:0] icmp_ln1162_fu_1141_p2;
reg   [0:0] icmp_ln1162_reg_1578;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire   [0:0] state_execute_alu_results_exception_0_load_load_fu_723_p1;
wire   [4:0] state_rob_entries_memory_completed_addr_1_gep_fu_466_p3;
wire   [63:0] zext_ln1200_fu_851_p1;
wire   [63:0] zext_ln1210_fu_881_p1;
wire   [63:0] zext_ln1134_fu_959_p1;
wire   [63:0] zext_ln1144_fu_969_p1;
wire   [0:0] icmp_ln1143_fu_964_p2;
wire   [63:0] zext_ln1145_fu_977_p1;
wire   [63:0] zext_ln1164_fu_1159_p1;
wire   [4:0] grp_fu_669_p2;
wire    ap_CS_fsm_state21;
reg    ap_predicate_op256_write_state18;
reg    ap_block_state18;
wire   [31:0] add_ln1176_fu_760_p2;
reg    ap_predicate_op139_write_state13;
reg    ap_block_state13;
wire   [63:0] add_ln1194_fu_839_p2;
wire   [7:0] zext_ln1147_fu_1027_p1;
wire   [5:0] select_ln1146_fu_1008_p3;
reg   [31:0] i_fu_180;
reg   [5:0] idx_3_fu_184;
wire   [5:0] idx_4_fu_1066_p3;
reg   [4:0] grp_fu_669_p0;
wire   [2:0] tmp_1_fu_702_p4;
wire   [0:0] icmp_ln1157_fu_735_p2;
wire  signed [4:0] sext_ln173_fu_776_p0;
wire  signed [4:0] tmp_4_fu_780_p1;
wire   [60:0] tmp_4_fu_780_p4;
wire   [7:0] zext_ln1175_fu_772_p1;
wire   [63:0] tmp_5_fu_794_p4;
wire  signed [63:0] sext_ln173_1_fu_790_p1;
wire  signed [7:0] sext_ln173_fu_776_p1;
wire   [63:0] or_ln173_fu_804_p2;
wire   [282:0] tmp3_fu_810_p8;
wire   [0:0] icmp_ln1197_fu_856_p2;
wire   [0:0] icmp_ln1211_fu_886_p2;
wire   [0:0] icmp_ln1211_1_fu_892_p2;
wire   [0:0] icmp_ln1133_fu_933_p2;
wire   [0:0] icmp_ln1133_1_fu_938_p2;
wire   [6:0] zext_ln1146_fu_982_p1;
wire   [6:0] add_ln1146_fu_986_p2;
wire   [0:0] icmp_ln1146_fu_992_p2;
wire   [5:0] trunc_ln1146_fu_1004_p1;
wire   [5:0] add_ln1146_1_fu_998_p2;
wire   [5:0] add_ln1147_fu_1022_p2;
wire   [6:0] zext_ln1135_fu_1042_p1;
wire   [6:0] add_ln1135_fu_1045_p2;
wire   [0:0] icmp_ln1135_fu_1051_p2;
wire   [5:0] trunc_ln1135_fu_1062_p1;
wire   [5:0] add_ln1135_1_fu_1057_p2;
wire   [68:0] tmp_9_fu_1083_p3;
wire  signed [71:0] sext_ln173_2_fu_1089_p1;
wire   [514:0] tmp_s_fu_1093_p17;
wire   [514:0] or_ln173_2_fu_1118_p2;
wire    ap_CS_fsm_state22;
reg   [21:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln1211_fu_898_p2) & (1'b1 == ap_CS_fsm_state16))) begin
        i_fu_180 <= 32'd0;
    end else if ((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (icmp_ln1209_reg_1462 == 1'd1) & (icmp_ln1134_fu_1037_p2 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd1 == and_ln1211_reg_1521) & (1'd1 == and_ln1133_reg_1552) & (1'b1 == ap_CS_fsm_state18))) begin
        i_fu_180 <= i_4_reg_1556;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln1211_fu_898_p2) & (1'b1 == ap_CS_fsm_state16))) begin
        idx_3_fu_184 <= state_rename_int_free_list_head;
    end else if ((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (icmp_ln1209_reg_1462 == 1'd1) & (icmp_ln1134_fu_1037_p2 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd1 == and_ln1211_reg_1521) & (1'd1 == and_ln1133_reg_1552) & (1'b1 == ap_CS_fsm_state18))) begin
        idx_3_fu_184 <= idx_4_fu_1066_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        and_ln1133_reg_1552 <= and_ln1133_fu_944_p2;
        i_4_reg_1556 <= i_4_fu_950_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        and_ln1211_reg_1521 <= and_ln1211_fu_898_p2;
        preg_reg_1514 <= state_rob_entries_uop_rename_stale_pdst_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ce_inst_reg_1457 <= state_rob_entries_uop_inst_q0;
        ce_is_store_reg_1486 <= state_rob_entries_is_store_q0;
        ce_memory_address_reg_1491 <= state_rob_entries_memory_address_q0;
        ce_memory_data_reg_1497 <= state_rob_entries_memory_data_q0;
        ce_memory_mask_reg_1503 <= state_rob_entries_memory_mask_q0;
        ce_memory_valid_reg_1481 <= state_rob_entries_memory_valid_q0;
        ce_pc_reg_1452 <= state_rob_entries_uop_debug_pc_q0;
        ce_rd_reg_1471 <= state_rob_entries_uop_rename_ldst_q0;
        ce_rd_valid_reg_1466 <= ce_rd_valid_fu_867_p2;
        ce_rd_value_reg_1476 <= ce_rd_value_fu_873_p3;
        icmp_ln1209_reg_1462 <= icmp_ln1209_fu_862_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln1211_fu_898_p2) & (1'b1 == ap_CS_fsm_state16))) begin
        conv_i_i_reg_1547[7 : 0] <= conv_i_i_fu_916_p1[7 : 0];
        empty_reg_1542 <= empty_fu_912_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        icmp_ln1162_reg_1578 <= icmp_ln1162_fu_1141_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((state_execute_alu_results_uop_ctrl_is_sta_0_load_load_fu_694_p1 == 1'd0) & (state_execute_alu_results_uop_ctrl_is_load_0_load_load_fu_690_p1 == 1'd0) & (state_execute_alu_results_is_store_0_load_load_fu_686_p1 == 1'd0) & (state_execute_alu_results_is_load_0_load_load_fu_682_p1 == 1'd0) & (state_execute_alu_results_memory_valid_0_load_load_fu_678_p1 == 1'd0) & (state_execute_alu_results_valid_0_load_load_fu_674_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln477_reg_1206 <= icmp_ln477_fu_712_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        state_rob_entries_exception_load_reg_1288 <= state_rob_entries_exception_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((state_rob_entries_uop_ctrl_is_load_load_reg_1302 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        state_rob_entries_is_load_load_reg_1311 <= state_rob_entries_is_load_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((state_rob_entries_uop_ctrl_is_sta_load_reg_1328 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        state_rob_entries_is_store_load_reg_1337 <= state_rob_entries_is_store_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (state_rob_entries_memory_valid_q0 == 1'd1))) begin
        state_rob_entries_memory_request_sent_addr_reg_1349 <= zext_ln1158_reg_1235;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_memory_request_sent_load_reg_1354 <= state_rob_entries_memory_request_sent_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_rob_entries_uop_ctrl_is_load_load_reg_1302 <= state_rob_entries_uop_ctrl_is_load_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        state_rob_entries_uop_ctrl_is_sta_load_reg_1328 <= state_rob_entries_uop_ctrl_is_sta_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_uop_rename_pdst_load_reg_1411 <= state_rob_entries_uop_rename_pdst_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln1157_fu_745_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        state_rob_entries_valid_addr_2_reg_1267 <= zext_ln1158_fu_751_p1;
        zext_ln1158_reg_1235[4 : 0] <= zext_ln1158_fu_751_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        state_rob_head_load_reg_1227 <= state_rob_head_i;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln477_fu_712_p2 == 1'd1) & (state_execute_alu_results_uop_ctrl_is_sta_0_load_load_fu_694_p1 == 1'd0) & (state_execute_alu_results_uop_ctrl_is_load_0_load_load_fu_690_p1 == 1'd0) & (state_execute_alu_results_is_store_0_load_load_fu_686_p1 == 1'd0) & (state_execute_alu_results_is_load_0_load_load_fu_682_p1 == 1'd0) & (state_execute_alu_results_memory_valid_0_load_load_fu_678_p1 == 1'd0) & (state_execute_alu_results_valid_0_load_load_fu_674_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        zext_ln477_reg_1210[7 : 0] <= zext_ln477_fu_718_p1[7 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if (((ap_predicate_op139_write_state13 == 1'b1) & (pipe_2_full_n == 1'b0))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if (((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0))) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_669_p0 = state_rob_head_load_reg_1227;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_669_p0 = state_rob_head_i;
    end else begin
        grp_fu_669_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (((state_rob_entries_uop_ctrl_is_sta_load_reg_1328 == 1'd1) & (state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0)) | ((state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0) & (state_rob_entries_is_store_load_reg_1337 == 1'd1))))) begin
        pipe_2_blk_n = pipe_2_full_n;
    end else begin
        pipe_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op139_write_state13 == 1'b1) & (pipe_2_full_n == 1'b0)) & (ap_predicate_op139_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        pipe_2_write = 1'b1;
    end else begin
        pipe_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (((((tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (icmp_ln1134_fu_1037_p2 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)) | ((tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1133_reg_1552))) | ((tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1211_reg_1521))) | ((icmp_ln1209_reg_1462 == 1'd0) & (tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0))))) begin
        pipe_4_blk_n = pipe_4_full_n;
    end else begin
        pipe_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (ap_predicate_op256_write_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        pipe_4_write = 1'b1;
    end else begin
        pipe_4_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        state_csr_instret_o = add_ln1194_fu_839_p2;
    end else begin
        state_csr_instret_o = state_csr_instret_i;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op139_write_state13 == 1'b1) & (pipe_2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        state_csr_instret_o_ap_vld = 1'b1;
    end else begin
        state_csr_instret_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        state_int_rf_address0 = zext_ln1164_fu_1159_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        state_int_rf_address0 = zext_ln1200_fu_851_p1;
    end else begin
        state_int_rf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state14))) begin
        state_int_rf_ce0 = 1'b1;
    end else begin
        state_int_rf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (((state_rob_entries_uop_ctrl_is_sta_load_reg_1328 == 1'd1) & (state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0)) | ((state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0) & (state_rob_entries_is_store_load_reg_1337 == 1'd1))))) begin
        state_lsu_next_transaction_id_o = add_ln1176_fu_760_p2;
    end else begin
        state_lsu_next_transaction_id_o = state_lsu_next_transaction_id_i;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op139_write_state13 == 1'b1) & (pipe_2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13) & (((state_rob_entries_uop_ctrl_is_sta_load_reg_1328 == 1'd1) & (state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0)) | ((state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0) & (state_rob_entries_is_store_load_reg_1337 == 1'd1))))) begin
        state_lsu_next_transaction_id_o_ap_vld = 1'b1;
    end else begin
        state_lsu_next_transaction_id_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        state_rename_int_free_list_busy_table_ce0 = 1'b1;
    end else begin
        state_rename_int_free_list_busy_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        state_rename_int_free_list_busy_table_we0 = 1'b1;
    end else begin
        state_rename_int_free_list_busy_table_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        state_rename_int_free_list_count_o = zext_ln1147_fu_1027_p1;
    end else begin
        state_rename_int_free_list_count_o = state_rename_int_free_list_count_i;
    end
end

always @ (*) begin
    if (((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        state_rename_int_free_list_count_o_ap_vld = 1'b1;
    end else begin
        state_rename_int_free_list_count_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        if (((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2))) begin
            state_rename_int_free_list_free_list_address0 = zext_ln1145_fu_977_p1;
        end else if ((1'd1 == and_ln1133_fu_944_p2)) begin
            state_rename_int_free_list_free_list_address0 = zext_ln1134_fu_959_p1;
        end else begin
            state_rename_int_free_list_free_list_address0 = 'bx;
        end
    end else begin
        state_rename_int_free_list_free_list_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17)) | ((1'd1 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17)))) begin
        state_rename_int_free_list_free_list_ce0 = 1'b1;
    end else begin
        state_rename_int_free_list_free_list_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        state_rename_int_free_list_free_list_we0 = 1'b1;
    end else begin
        state_rename_int_free_list_free_list_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        state_rename_int_free_list_tail_o = select_ln1146_fu_1008_p3;
    end else begin
        state_rename_int_free_list_tail_o = state_rename_int_free_list_tail_i;
    end
end

always @ (*) begin
    if (((icmp_ln1143_fu_964_p2 == 1'd0) & (1'd0 == and_ln1133_fu_944_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        state_rename_int_free_list_tail_o_ap_vld = 1'b1;
    end else begin
        state_rename_int_free_list_tail_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        state_rename_int_map_table_committed_map_table_ce0 = 1'b1;
    end else begin
        state_rename_int_map_table_committed_map_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1209_fu_862_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        state_rename_int_map_table_committed_map_table_we0 = 1'b1;
    end else begin
        state_rename_int_map_table_committed_map_table_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        state_rename_int_map_table_map_table_ce0 = 1'b1;
    end else begin
        state_rename_int_map_table_map_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        state_rob_entries_busy_address0 = zext_ln1158_reg_1235;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_rob_entries_busy_address0 = zext_ln477_reg_1210;
    end else begin
        state_rob_entries_busy_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        state_rob_entries_busy_ce0 = 1'b1;
    end else begin
        state_rob_entries_busy_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((state_rob_entries_valid_q0 == 1'd1) & (icmp_ln477_reg_1206 == 1'd1) & (state_execute_alu_results_uop_ctrl_is_sta_0_load_load_fu_694_p1 == 1'd0) & (state_execute_alu_results_uop_ctrl_is_load_0_load_load_fu_690_p1 == 1'd0) & (state_execute_alu_results_is_store_0_load_load_fu_686_p1 == 1'd0) & (state_execute_alu_results_is_load_0_load_load_fu_682_p1 == 1'd0) & (state_execute_alu_results_memory_valid_0_load_load_fu_678_p1 == 1'd0) & (state_execute_alu_results_valid_0_load_load_fu_674_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        state_rob_entries_busy_we0 = 1'b1;
    end else begin
        state_rob_entries_busy_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_rob_entries_exception_address0 = zext_ln1158_reg_1235;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_rob_entries_exception_address0 = zext_ln477_reg_1210;
    end else begin
        state_rob_entries_exception_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        state_rob_entries_exception_ce0 = 1'b1;
    end else begin
        state_rob_entries_exception_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((state_rob_entries_valid_q0 == 1'd1) & (state_execute_alu_results_exception_0_load_load_fu_723_p1 == 1'd1) & (icmp_ln477_reg_1206 == 1'd1) & (state_execute_alu_results_uop_ctrl_is_sta_0_load_load_fu_694_p1 == 1'd0) & (state_execute_alu_results_uop_ctrl_is_load_0_load_load_fu_690_p1 == 1'd0) & (state_execute_alu_results_is_store_0_load_load_fu_686_p1 == 1'd0) & (state_execute_alu_results_is_load_0_load_load_fu_682_p1 == 1'd0) & (state_execute_alu_results_memory_valid_0_load_load_fu_678_p1 == 1'd0) & (state_execute_alu_results_valid_0_load_load_fu_674_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        state_rob_entries_exception_we0 = 1'b1;
    end else begin
        state_rob_entries_exception_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        state_rob_entries_is_load_ce0 = 1'b1;
    end else begin
        state_rob_entries_is_load_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_is_store_address0 = state_rob_entries_is_store_addr_1_gep_fu_561_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        state_rob_entries_is_store_address0 = zext_ln1158_reg_1235;
    end else begin
        state_rob_entries_is_store_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state9))) begin
        state_rob_entries_is_store_ce0 = 1'b1;
    end else begin
        state_rob_entries_is_store_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_memory_address_address0 = state_rob_entries_memory_address_addr_1_gep_fu_569_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_memory_address_address0 = zext_ln1158_reg_1235;
    end else begin
        state_rob_entries_memory_address_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12))) begin
        state_rob_entries_memory_address_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_address_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_memory_completed_address0 = state_rob_entries_memory_completed_addr_1_gep_fu_466_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        state_rob_entries_memory_completed_address0 = zext_ln1158_reg_1235;
    end else begin
        state_rob_entries_memory_completed_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state7))) begin
        state_rob_entries_memory_completed_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_completed_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbwritereq_fu_188_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (state_rob_entries_memory_request_sent_q0 == 1'd0))) begin
        state_rob_entries_memory_completed_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_completed_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_memory_data_address0 = state_rob_entries_memory_data_addr_1_gep_fu_577_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_memory_data_address0 = zext_ln1158_reg_1235;
    end else begin
        state_rob_entries_memory_data_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12))) begin
        state_rob_entries_memory_data_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_memory_mask_address0 = state_rob_entries_memory_mask_addr_1_gep_fu_585_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_memory_mask_address0 = zext_ln1158_reg_1235;
    end else begin
        state_rob_entries_memory_mask_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12))) begin
        state_rob_entries_memory_mask_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_mask_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_memory_request_sent_address0 = state_rob_entries_memory_request_sent_addr_reg_1349;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        state_rob_entries_memory_request_sent_address0 = zext_ln1158_reg_1235;
    end else begin
        state_rob_entries_memory_request_sent_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        state_rob_entries_memory_request_sent_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_request_sent_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbwritereq_fu_188_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (state_rob_entries_memory_request_sent_q0 == 1'd0))) begin
        state_rob_entries_memory_request_sent_we0 = 1'b1;
    end else begin
        state_rob_entries_memory_request_sent_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_memory_size_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_size_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_memory_valid_address0 = state_rob_entries_memory_valid_addr_1_gep_fu_553_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        state_rob_entries_memory_valid_address0 = zext_ln1158_reg_1235;
    end else begin
        state_rob_entries_memory_valid_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state10))) begin
        state_rob_entries_memory_valid_ce0 = 1'b1;
    end else begin
        state_rob_entries_memory_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_uop_branch_br_mask_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_branch_br_mask_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        state_rob_entries_uop_ctrl_is_load_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_ctrl_is_load_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        state_rob_entries_uop_ctrl_is_sta_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_ctrl_is_sta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_uop_debug_pc_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_debug_pc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_uop_inst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_inst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        state_rob_entries_uop_queue_rob_idx_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_queue_rob_idx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_uop_rename_dst_rtype_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_dst_rtype_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        state_rob_entries_uop_rename_ldst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_ldst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op139_write_state13 == 1'b1) & (pipe_2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        state_rob_entries_uop_rename_pdst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_pdst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        state_rob_entries_uop_rename_stale_pdst_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_rename_stale_pdst_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        state_rob_entries_uop_uopc_ce0 = 1'b1;
    end else begin
        state_rob_entries_uop_uopc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state18))) begin
        state_rob_entries_valid_address0 = state_rob_entries_valid_addr_2_reg_1267;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        state_rob_entries_valid_address0 = zext_ln1158_fu_751_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        state_rob_entries_valid_address0 = zext_ln477_fu_718_p1;
    end else begin
        state_rob_entries_valid_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18)))) begin
        state_rob_entries_valid_ce0 = 1'b1;
    end else begin
        state_rob_entries_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18) & (((((icmp_ln1134_fu_1037_p2 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1133_reg_1552))) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1211_reg_1521))) | ((icmp_ln1209_reg_1462 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0)))) | ((icmp_ln1162_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state21)))) begin
        state_rob_entries_valid_we0 = 1'b1;
    end else begin
        state_rob_entries_valid_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1162_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state18) & (((((icmp_ln1134_fu_1037_p2 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1133_reg_1552))) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1211_reg_1521))) | ((icmp_ln1209_reg_1462 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0)))))) begin
        state_rob_head_o = grp_fu_669_p2;
    end else begin
        state_rob_head_o = state_rob_head_i;
    end
end

always @ (*) begin
    if (((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18) & (((((icmp_ln1134_fu_1037_p2 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1133_reg_1552))) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1211_reg_1521))) | ((icmp_ln1209_reg_1462 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0)))) | ((icmp_ln1162_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state21)))) begin
        state_rob_head_o_ap_vld = 1'b1;
    end else begin
        state_rob_head_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1162_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state21)) | ((1'b1 == ap_CS_fsm_state18) & (((((icmp_ln1134_fu_1037_p2 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1133_reg_1552))) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1211_reg_1521))) | ((icmp_ln1209_reg_1462 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0)))))) begin
        state_rob_maybe_full_o = 1'd0;
    end else begin
        state_rob_maybe_full_o = state_rob_maybe_full_i;
    end
end

always @ (*) begin
    if (((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18) & (((((icmp_ln1134_fu_1037_p2 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1133_reg_1552))) | ((state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1211_reg_1521))) | ((icmp_ln1209_reg_1462 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0)))) | ((icmp_ln1162_reg_1578 == 1'd1) & (1'b1 == ap_CS_fsm_state21)))) begin
        state_rob_maybe_full_o_ap_vld = 1'b1;
    end else begin
        state_rob_maybe_full_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1162_fu_1141_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        state_rob_state_ap_vld = 1'b1;
    end else begin
        state_rob_state_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((or_ln1157_fu_745_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((state_rob_entries_valid_q0 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((state_rob_entries_busy_q0 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((state_rob_entries_exception_q0 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (((state_rob_entries_is_load_load_reg_1311 == 1'd1) & (state_rob_entries_memory_completed_q0 == 1'd0)) | ((state_rob_entries_uop_ctrl_is_load_load_reg_1302 == 1'd1) & (state_rob_entries_memory_completed_q0 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((state_rob_entries_uop_ctrl_is_sta_load_reg_1328 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (state_rob_entries_is_store_q0 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (state_rob_entries_memory_valid_q0 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((tmp_nbwritereq_fu_188_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (state_rob_entries_memory_request_sent_q0 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if ((~((ap_predicate_op139_write_state13 == 1'b1) & (pipe_2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln1209_fu_862_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'd1 == and_ln1211_fu_898_p2) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if ((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18) & ((state_rob_entries_exception_load_reg_1288 == 1'd1) | ((icmp_ln1209_reg_1462 == 1'd0) | ((1'd0 == and_ln1211_reg_1521) | ((icmp_ln1134_fu_1037_p2 == 1'd1) | (1'd0 == and_ln1133_reg_1552))))))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else if ((~((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0)) & (icmp_ln1209_reg_1462 == 1'd1) & (icmp_ln1134_fu_1037_p2 == 1'd0) & (state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd1 == and_ln1211_reg_1521) & (1'd1 == and_ln1133_reg_1552) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln1162_fu_1141_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1135_1_fu_1057_p2 = (idx_3_fu_184 + 6'd13);

assign add_ln1135_fu_1045_p2 = (zext_ln1135_fu_1042_p1 + 7'd1);

assign add_ln1146_1_fu_998_p2 = (state_rename_int_free_list_tail_i + 6'd13);

assign add_ln1146_fu_986_p2 = (zext_ln1146_fu_982_p1 + 7'd1);

assign add_ln1147_fu_1022_p2 = (empty_reg_1542 + 6'd1);

assign add_ln1176_fu_760_p2 = (state_lsu_next_transaction_id_i + 32'd1);

assign add_ln1194_fu_839_p2 = (state_csr_instret_i + 64'd1);

assign and_ln1133_fu_944_p2 = (icmp_ln1133_fu_933_p2 & icmp_ln1133_1_fu_938_p2);

assign and_ln1211_fu_898_p2 = (icmp_ln1211_fu_886_p2 & icmp_ln1211_1_fu_892_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state13 = ((ap_predicate_op139_write_state13 == 1'b1) & (pipe_2_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state18 = ((ap_predicate_op256_write_state18 == 1'b1) & (pipe_4_full_n == 1'b0));
end

always @ (*) begin
    ap_predicate_op139_write_state13 = (((state_rob_entries_uop_ctrl_is_sta_load_reg_1328 == 1'd1) & (state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0)) | ((state_rob_entries_memory_request_sent_load_reg_1354 == 1'd0) & (state_rob_entries_is_store_load_reg_1337 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op256_write_state18 = (((((tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (icmp_ln1134_fu_1037_p2 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)) | ((tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1133_reg_1552))) | ((tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0) & (1'd0 == and_ln1211_reg_1521))) | ((icmp_ln1209_reg_1462 == 1'd0) & (tmp_7_nbwritereq_fu_203_p3 == 1'd1) & (state_rob_entries_exception_load_reg_1288 == 1'd0)));
end

assign ce_rd_valid_fu_867_p2 = (icmp_ln1209_fu_862_p2 & icmp_ln1197_fu_856_p2);

assign ce_rd_value_fu_873_p3 = ((ce_rd_valid_fu_867_p2[0:0] == 1'b1) ? state_int_rf_q0 : 64'd0);

assign conv_i_i_fu_916_p1 = state_rename_int_free_list_count_i;

assign empty_fu_912_p1 = state_rename_int_free_list_count_i[5:0];

assign grp_fu_669_p2 = (grp_fu_669_p0 + 5'd1);

assign i_4_fu_950_p2 = (i_fu_180 + 32'd1);

assign icmp_ln1133_1_fu_938_p2 = (($signed(i_fu_180) < $signed(32'd52)) ? 1'b1 : 1'b0);

assign icmp_ln1133_fu_933_p2 = (($signed(i_fu_180) < $signed(conv_i_i_reg_1547)) ? 1'b1 : 1'b0);

assign icmp_ln1134_fu_1037_p2 = ((state_rename_int_free_list_free_list_q0 == preg_reg_1514) ? 1'b1 : 1'b0);

assign icmp_ln1135_fu_1051_p2 = ((add_ln1135_fu_1045_p2 < 7'd52) ? 1'b1 : 1'b0);

assign icmp_ln1143_fu_964_p2 = ((state_rename_int_free_list_count_i > 8'd51) ? 1'b1 : 1'b0);

assign icmp_ln1146_fu_992_p2 = ((add_ln1146_fu_986_p2 < 7'd52) ? 1'b1 : 1'b0);

assign icmp_ln1157_fu_735_p2 = ((state_rob_head_i != state_rob_tail) ? 1'b1 : 1'b0);

assign icmp_ln1162_fu_1141_p2 = ((state_rob_entries_uop_uopc_q0 == 8'd65) ? 1'b1 : 1'b0);

assign icmp_ln1197_fu_856_p2 = ((state_rob_entries_uop_rename_dst_rtype_q0 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1209_fu_862_p2 = ((state_rob_entries_uop_rename_pdst_load_reg_1411 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1211_1_fu_892_p2 = ((state_rob_entries_uop_rename_stale_pdst_q0 < 8'd52) ? 1'b1 : 1'b0);

assign icmp_ln1211_fu_886_p2 = ((state_rob_entries_uop_rename_stale_pdst_q0 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln477_fu_712_p2 = ((tmp_1_fu_702_p4 == 3'd0) ? 1'b1 : 1'b0);

assign idx_4_fu_1066_p3 = ((icmp_ln1135_fu_1051_p2[0:0] == 1'b1) ? trunc_ln1135_fu_1062_p1 : add_ln1135_1_fu_1057_p2);

assign or_ln1157_fu_745_p2 = (state_rob_maybe_full_i | icmp_ln1157_fu_735_p2);

assign or_ln173_2_fu_1118_p2 = (tmp_s_fu_1093_p17 | 515'd121694457621910022543683507716097);

assign or_ln173_fu_804_p2 = (tmp_5_fu_794_p4 | sext_ln173_1_fu_790_p1);

assign pipe_2_din = (tmp3_fu_810_p8 | 283'd1547425049106726443135533056);

assign pipe_4_din = $signed(or_ln173_2_fu_1118_p2);

assign select_ln1146_fu_1008_p3 = ((icmp_ln1146_fu_992_p2[0:0] == 1'b1) ? trunc_ln1146_fu_1004_p1 : add_ln1146_1_fu_998_p2);

assign sext_ln173_1_fu_790_p1 = $signed(tmp_4_fu_780_p4);

assign sext_ln173_2_fu_1089_p1 = $signed(tmp_9_fu_1083_p3);

assign sext_ln173_fu_776_p0 = state_rob_entries_memory_mask_q0;

assign sext_ln173_fu_776_p1 = sext_ln173_fu_776_p0;

assign state_execute_alu_results_exception_0_load_load_fu_723_p1 = state_execute_alu_results_exception_0;

assign state_execute_alu_results_is_load_0_load_load_fu_682_p1 = state_execute_alu_results_is_load_0;

assign state_execute_alu_results_is_store_0_load_load_fu_686_p1 = state_execute_alu_results_is_store_0;

assign state_execute_alu_results_memory_valid_0_load_load_fu_678_p1 = state_execute_alu_results_memory_valid_0;

assign state_execute_alu_results_uop_ctrl_is_load_0_load_load_fu_690_p1 = state_execute_alu_results_uop_ctrl_is_load_0;

assign state_execute_alu_results_uop_ctrl_is_sta_0_load_load_fu_694_p1 = state_execute_alu_results_uop_ctrl_is_sta_0;

assign state_execute_alu_results_valid_0_load_load_fu_674_p1 = state_execute_alu_results_valid_0;

assign state_rename_int_free_list_busy_table_address0 = zext_ln1144_fu_969_p1;

assign state_rename_int_free_list_busy_table_d0 = 1'd0;

assign state_rename_int_free_list_free_list_d0 = preg_reg_1514;

assign state_rename_int_map_table_committed_map_table_address0 = zext_ln1210_fu_881_p1;

assign state_rename_int_map_table_committed_map_table_d0 = state_rob_entries_uop_rename_pdst_load_reg_1411;

assign state_rename_int_map_table_map_table_address0 = 5'd10;

assign state_rob_entries_busy_d0 = 1'd0;

assign state_rob_entries_exception_d0 = 1'd1;

assign state_rob_entries_is_load_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_is_store_addr_1_gep_fu_561_p3 = zext_ln1158_reg_1235;

assign state_rob_entries_memory_address_addr_1_gep_fu_569_p3 = zext_ln1158_reg_1235;

assign state_rob_entries_memory_completed_addr_1_gep_fu_466_p3 = zext_ln1158_reg_1235;

assign state_rob_entries_memory_completed_d0 = 1'd1;

assign state_rob_entries_memory_data_addr_1_gep_fu_577_p3 = zext_ln1158_reg_1235;

assign state_rob_entries_memory_mask_addr_1_gep_fu_585_p3 = zext_ln1158_reg_1235;

assign state_rob_entries_memory_request_sent_d0 = 1'd1;

assign state_rob_entries_memory_size_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_memory_valid_addr_1_gep_fu_553_p3 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_branch_br_mask_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_ctrl_is_load_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_ctrl_is_sta_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_debug_pc_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_inst_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_queue_rob_idx_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_rename_dst_rtype_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_rename_ldst_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_rename_pdst_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_rename_stale_pdst_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_uop_uopc_address0 = zext_ln1158_reg_1235;

assign state_rob_entries_valid_d0 = 1'd0;

assign state_rob_state = 2'd3;

assign tmp3_fu_810_p8 = {{{{{{{state_rob_entries_memory_data_q0}, {state_rob_entries_memory_data_q0}}, {state_rob_entries_memory_address_q0}}, {11'd0}}, {state_rob_entries_uop_branch_br_mask_q0}}, {sext_ln173_fu_776_p1}}, {or_ln173_fu_804_p2}};

assign tmp_1_fu_702_p4 = {{state_execute_alu_results_uop_queue_rob_idx_0[7:5]}};

assign tmp_4_fu_780_p1 = state_rob_entries_memory_mask_q0;

assign tmp_4_fu_780_p4 = {{{tmp_4_fu_780_p1}, {state_rob_entries_memory_size_q0}}, {48'd0}};

assign tmp_5_fu_794_p4 = {{{{24'd0}, {zext_ln1175_fu_772_p1}}}, {state_lsu_next_transaction_id_i}};

assign tmp_7_nbwritereq_fu_203_p3 = pipe_4_full_n;

assign tmp_9_fu_1083_p3 = {{ce_memory_mask_reg_1503}, {ce_memory_data_reg_1497}};

assign tmp_nbwritereq_fu_188_p3 = pipe_2_full_n;

assign tmp_s_fu_1093_p17 = {{{{{{{{{{{{{{{{ce_memory_mask_reg_1503}, {sext_ln173_2_fu_1089_p1}}, {ce_memory_address_reg_1491}}, {ce_memory_data_reg_1497}}, {ce_memory_address_reg_1491}}, {ce_is_store_reg_1486}}, {ce_memory_valid_reg_1481}}, {65'd0}}, {ce_rd_valid_reg_1466}}, {1'd0}}, {ce_rd_value_reg_1476}}, {11'd0}}, {ce_rd_reg_1471}}, {ce_inst_reg_1457}}, {ce_pc_reg_1452}}, {1'd0}};

assign trunc_ln1135_fu_1062_p1 = add_ln1135_fu_1045_p2[5:0];

assign trunc_ln1146_fu_1004_p1 = add_ln1146_fu_986_p2[5:0];

assign zext_ln1134_fu_959_p1 = idx_3_fu_184;

assign zext_ln1135_fu_1042_p1 = idx_3_fu_184;

assign zext_ln1144_fu_969_p1 = preg_reg_1514;

assign zext_ln1145_fu_977_p1 = state_rename_int_free_list_tail_i;

assign zext_ln1146_fu_982_p1 = state_rename_int_free_list_tail_i;

assign zext_ln1147_fu_1027_p1 = add_ln1147_fu_1022_p2;

assign zext_ln1158_fu_751_p1 = state_rob_head_i;

assign zext_ln1164_fu_1159_p1 = state_rename_int_map_table_map_table_q0;

assign zext_ln1175_fu_772_p1 = state_rob_entries_uop_queue_rob_idx_q0;

assign zext_ln1200_fu_851_p1 = state_rob_entries_uop_rename_pdst_q0;

assign zext_ln1210_fu_881_p1 = state_rob_entries_uop_rename_ldst_q0;

assign zext_ln477_fu_718_p1 = state_execute_alu_results_uop_queue_rob_idx_0;

always @ (posedge ap_clk) begin
    zext_ln477_reg_1210[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln1158_reg_1235[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    conv_i_i_reg_1547[31:8] <= 24'b000000000000000000000000;
end

endmodule //boom_core_top_rob_commit_module
