#!/bin/bash
# AUTO-GENERATED merged file generator for Vitis HLS
# Generates src/boom_core_merged.cpp from individual source files

set -e
BASE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$BASE/src/boom_core_merged.cpp"

cat > "$OUT" << 'HEAD'
// AUTO-GENERATED by scripts/generate_merged.sh
// Do NOT edit manually. Edit individual source files instead.

#include "boom_config.hpp"
#include "boom_types.hpp"
#include "boom_state.hpp"
#include "boom_interfaces.hpp"
#include <cstdint>

#define UOPC_MERGED_NOP 0
#define UOPC_MERGED_ADD 1
#define UOPC_MERGED_SUB 2
#define UOPC_MERGED_ILLEGAL 255
HEAD

echo "" >> "$OUT"
echo "// ==== frontend.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/frontend.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== decode.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/decode.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== rename.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/rename.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== issue.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/issue.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== execute.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/execute.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== branch.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/branch.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== lsu.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/lsu.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== csr.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/csr.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== boom_core_step.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/boom_core_step.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== boom_core_top.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/boom_core_top.cpp" >> "$OUT"

echo "Generated $OUT ($(wc -l < "$OUT") lines)"
