#!/bin/bash
# AUTO-GENERATED merged file generator for Vitis HLS
# Generates src/boom_core_merged.cpp from individual source files

set -e
BASE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$BASE/src/boom_core_merged.cpp"

cat > "$OUT" << 'HEAD'
// AUTO-GENERATED by scripts/generate_merged.sh
// Do NOT edit manually. Edit individual source files instead.

#include "boom_config.hpp"
#include "boom_types.hpp"
#include "boom_state.hpp"
#include "boom_interfaces.hpp"
#include "issue.hpp"
#include "reset.hpp"
#include "completion.hpp"
#include "mul.hpp"
#include "divider.hpp"
#include "fetch_buffer.hpp"
#include "fetch_packet.hpp"
#include "rvc.hpp"
#include "predecode.hpp"
#if defined(BOOM_USE_AP_INT) || defined(__SYNTHESIS__)
#include <ap_int.h>
#endif
#include <cstdint>

#define UOPC_MERGED_NOP 0
#define UOPC_MERGED_ADD 1
#define UOPC_MERGED_SUB 2
#define UOPC_MERGED_ILLEGAL 255
HEAD

echo "" >> "$OUT"
echo "// ==== fetch_buffer.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/fetch_buffer.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== fetch_packet.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/fetch_packet.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== predecode.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/predecode.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== frontend.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/frontend.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== decode.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/decode.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== rvc.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/rvc.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== rename.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/rename.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== completion.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/completion.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== rob.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/rob.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== issue.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/issue.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== mul.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/mul.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== divider.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/divider.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== execute.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/execute.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== branch.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/branch.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== lsu.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/lsu.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== commit.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/commit.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== csr.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/csr.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== boom_core_step.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/boom_core_step.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== reset.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/reset.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== boom_core_top.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/boom_core_top.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== synth_module_tops.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/synth_module_tops.cpp" >> "$OUT"
echo "" >> "$OUT"
echo "// ==== synth_rvc_top.cpp ====" >> "$OUT"
grep -v '#include' "$BASE/src/synth_rvc_top.cpp" >> "$OUT"

echo "Generated $OUT ($(wc -l < "$OUT") lines)"
