// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="synth_lsu_top_synth_lsu_top,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.474000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=102,HLS_SYN_LUT=129,HLS_VERSION=2021_2}" *)

module synth_lsu_top (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dmem_req_out_din,
        dmem_req_out_full_n,
        dmem_req_out_write,
        dmem_resp_in_dout,
        dmem_resp_in_empty_n,
        dmem_resp_in_read,
        seed_addr,
        observable,
        observable_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [282:0] dmem_req_out_din;
input   dmem_req_out_full_n;
output   dmem_req_out_write;
input  [288:0] dmem_resp_in_dout;
input   dmem_resp_in_empty_n;
output   dmem_resp_in_read;
input  [63:0] seed_addr;
output  [63:0] observable;
output   observable_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg dmem_req_out_write;
reg dmem_resp_in_read;
reg observable_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    dmem_req_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_1_nbreadreq_fu_81_p3;
reg    dmem_resp_in_blk_n;
wire   [0:0] tmp_nbreadreq_fu_60_p3;
reg    call_ln2052_lsu_module_fu_109_ap_start;
wire    call_ln2052_lsu_module_fu_109_ap_done;
wire    call_ln2052_lsu_module_fu_109_ap_idle;
wire    call_ln2052_lsu_module_fu_109_ap_ready;
wire    call_ln2052_lsu_module_fu_109_pipe_3_read;
wire    call_ln2052_lsu_module_fu_109_pipe_3_blk_n;
wire    pipe_2_empty_n;
reg    ap_block_state2_ignore_call0;
wire   [288:0] pipe_3_dout;
wire    pipe_3_empty_n;
reg    pipe_3_read;
wire    pipe_3_full_n;
reg    pipe_3_write;
reg    ap_block_state1;
reg    ap_block_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

synth_lsu_top_lsu_module call_ln2052_lsu_module_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln2052_lsu_module_fu_109_ap_start),
    .ap_done(call_ln2052_lsu_module_fu_109_ap_done),
    .ap_idle(call_ln2052_lsu_module_fu_109_ap_idle),
    .ap_ready(call_ln2052_lsu_module_fu_109_ap_ready),
    .pipe_3_dout(pipe_3_dout),
    .pipe_3_empty_n(pipe_3_empty_n),
    .pipe_3_read(call_ln2052_lsu_module_fu_109_pipe_3_read),
    .pipe_3_blk_n(call_ln2052_lsu_module_fu_109_pipe_3_blk_n)
);

synth_lsu_top_fifo_w289_d2_S pipe_3_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dmem_resp_in_dout),
    .if_full_n(pipe_3_full_n),
    .if_write(pipe_3_write),
    .if_dout(pipe_3_dout),
    .if_empty_n(pipe_3_empty_n),
    .if_read(pipe_3_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | ((pipe_3_full_n == 1'b0) & (tmp_nbreadreq_fu_60_p3 == 1'd1)) | ((tmp_nbreadreq_fu_60_p3 == 1'd1) & (dmem_resp_in_empty_n == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0)))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        call_ln2052_lsu_module_fu_109_ap_start = 1'b1;
    end else begin
        call_ln2052_lsu_module_fu_109_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1))) begin
        dmem_req_out_blk_n = dmem_req_out_full_n;
    end else begin
        dmem_req_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1))) begin
        dmem_req_out_write = 1'b1;
    end else begin
        dmem_req_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_60_p3 == 1'd1))) begin
        dmem_resp_in_blk_n = dmem_resp_in_empty_n;
    end else begin
        dmem_resp_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | ((pipe_3_full_n == 1'b0) & (tmp_nbreadreq_fu_60_p3 == 1'd1)) | ((tmp_nbreadreq_fu_60_p3 == 1'd1) & (dmem_resp_in_empty_n == 1'b0))) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_60_p3 == 1'd1))) begin
        dmem_resp_in_read = 1'b1;
    end else begin
        dmem_resp_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((~(((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        observable_ap_vld = 1'b1;
    end else begin
        observable_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        pipe_3_read = call_ln2052_lsu_module_fu_109_pipe_3_read;
    end else begin
        pipe_3_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | ((pipe_3_full_n == 1'b0) & (tmp_nbreadreq_fu_60_p3 == 1'd1)) | ((tmp_nbreadreq_fu_60_p3 == 1'd1) & (dmem_resp_in_empty_n == 1'b0))) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_60_p3 == 1'd1))) begin
        pipe_3_write = 1'b1;
    end else begin
        pipe_3_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | ((pipe_3_full_n == 1'b0) & (tmp_nbreadreq_fu_60_p3 == 1'd1)) | ((tmp_nbreadreq_fu_60_p3 == 1'd1) & (dmem_resp_in_empty_n == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((pipe_3_full_n == 1'b0) & (tmp_nbreadreq_fu_60_p3 == 1'd1)) | ((tmp_nbreadreq_fu_60_p3 == 1'd1) & (dmem_resp_in_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2 = (((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_ignore_call0 = (((pipe_2_empty_n == 1'b0) & (tmp_1_nbreadreq_fu_81_p3 == 1'd1)) | ((tmp_1_nbreadreq_fu_81_p3 == 1'd1) & (dmem_req_out_full_n == 1'b0)));
end

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign dmem_req_out_din = 283'd0;

assign observable = 64'd1;

assign pipe_2_empty_n = 1'b1;

assign tmp_1_nbreadreq_fu_81_p3 = pipe_2_empty_n;

assign tmp_nbreadreq_fu_60_p3 = dmem_resp_in_empty_n;

endmodule //synth_lsu_top
