// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module synth_lsu_top_lsu_module (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pipe_3_dout,
        pipe_3_empty_n,
        pipe_3_read,
        pipe_3_blk_n
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [288:0] pipe_3_dout;
input   pipe_3_empty_n;
output   pipe_3_read;
output   pipe_3_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg pipe_3_read;
reg pipe_3_blk_n;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_nbreadreq_fu_16_p3;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | ((tmp_nbreadreq_fu_16_p3 == 1'd1) & (pipe_3_empty_n == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | (~((ap_start == 1'b0) | ((tmp_nbreadreq_fu_16_p3 == 1'd1) & (pipe_3_empty_n == 1'b0))) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | ((tmp_nbreadreq_fu_16_p3 == 1'd1) & (pipe_3_empty_n == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (tmp_nbreadreq_fu_16_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        pipe_3_blk_n = pipe_3_empty_n;
    end else begin
        pipe_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | ((tmp_nbreadreq_fu_16_p3 == 1'd1) & (pipe_3_empty_n == 1'b0))) & (tmp_nbreadreq_fu_16_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        pipe_3_read = 1'b1;
    end else begin
        pipe_3_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_16_p3 == 1'd1) & (pipe_3_empty_n == 1'b0)));
end

assign tmp_nbreadreq_fu_16_p3 = pipe_3_empty_n;

endmodule //synth_lsu_top_lsu_module
