// AUTO-GENERATED by scripts/generate_merged.sh
// Do NOT edit manually. Edit individual source files instead.

#include "boom_config.hpp"
#include "boom_types.hpp"
#include "boom_state.hpp"
#include "boom_interfaces.hpp"
#include <cstdint>

#define UOPC_MERGED_NOP 0
#define UOPC_MERGED_ADD 1
#define UOPC_MERGED_SUB 2
#define UOPC_MERGED_ILLEGAL 255

// ==== frontend.cpp ====

namespace boom {

void frontend_module(BoomCoreState& state, PipeSignals& pipe) {
    FrontendState& fe = state.frontend;

    if (state.global_flush) {
        fe.flush = true;
        fe.request_sent = false;
        fe.fetch_packet_valid = false;
    }

    if (!fe.reset_done) {
        fe.pc = RESET_VECTOR;
        fe.fetch_id = 0;
        fe.reset_done = true;
        fe.request_sent = false;
    }

    if (state.brupdate.valid && state.brupdate.mispredict) {
        fe.pc = state.brupdate.jalr_target & ~0x3ULL;
        fe.request_sent = false;
        fe.response_received = false;
        fe.fetch_packet_valid = false;
        fe.flush = false;
        state.global_flush = false;
    }

    if (state.rob.state == ROB_EXCEPTION) {
        fe.pc = fe.pc;
        fe.fetch_packet_valid = false;
        return;
    }

    if (fe.flush) {
        fe.pc = state.brupdate.valid ? (state.brupdate.jalr_target & ~0x3ULL) : fe.pc;
        fe.request_sent = false;
        fe.response_received = false;
        fe.fetch_packet_valid = false;
        fe.flush = false;
        state.global_flush = false;
    }

    if (!fe.request_sent && fe.fetch_packet_valid) {
        fe.response_received = false;
        fe.fetch_packet_valid = false;
    }

    if (!fe.request_sent) {
        ImemRequest req;
        req.address = fe.pc;
        req.fetch_id = fe.fetch_id;
        req.kill = false;
        if (!pipe.imem_req.full()) {
            pipe.imem_req.write(req);
            fe.pending_fetch_id = fe.fetch_id;
            fe.fetch_id++;
            fe.request_sent = true;
        }
    }

    if (!pipe.imem_resp.empty()) {
        ImemResponse resp = pipe.imem_resp.read();
        if (fe.request_sent && resp.fetch_id == fe.pending_fetch_id) {
            fe.resp_address = resp.address;
            fe.resp_instruction = resp.instruction;
            fe.resp_exception = resp.exception;
            fe.resp_exc_cause = resp.exc_cause;
            fe.response_received = true;
            fe.request_sent = false;
        }
    }

    fe.fetch_packet_valid = false;
    if (fe.response_received && !fe.request_sent) {
        MicroOp uop;
        uop.debug_pc = fe.resp_address;
        uop.inst = fe.resp_instruction;
        uop.is_rvc = false;
        fe.fetch_uop = uop;
        fe.fetch_packet_valid = true;
        fe.pc = fe.resp_address + 4;
        fe.response_received = false;
    }

    state.frontend = fe;
}

}

// ==== decode.cpp ====

namespace boom {

#define UOPC_NOP      0
#define UOPC_ADD      1
#define UOPC_SUB      2
#define UOPC_SLL      3
#define UOPC_SLT      4
#define UOPC_SLTU     5
#define UOPC_XOR      6
#define UOPC_SRL      7
#define UOPC_SRA      8
#define UOPC_OR       9
#define UOPC_AND      10
#define UOPC_ADDW     11
#define UOPC_SUBW     12
#define UOPC_SLLW     13
#define UOPC_SRLW     14
#define UOPC_SRAW     15
#define UOPC_MUL      16
#define UOPC_MULH     17
#define UOPC_MULHSU   18
#define UOPC_MULHU    19
#define UOPC_MULW     20
#define UOPC_DIV      21
#define UOPC_DIVU     22
#define UOPC_REM      23
#define UOPC_REMU     24
#define UOPC_DIVW     25
#define UOPC_DIVUW    26
#define UOPC_REMW     27
#define UOPC_REMUW    28
#define UOPC_JAL      29
#define UOPC_JALR     30
#define UOPC_BEQ      31
#define UOPC_BNE      32
#define UOPC_BLT      33
#define UOPC_BGE      34
#define UOPC_BLTU     35
#define UOPC_BGEU     36
#define UOPC_LUI      37
#define UOPC_AUIPC    38
#define UOPC_LB       39
#define UOPC_LH       40
#define UOPC_LW       41
#define UOPC_LD       42
#define UOPC_LBU      43
#define UOPC_LHU      44
#define UOPC_LWU      45
#define UOPC_SB       46
#define UOPC_SH       47
#define UOPC_SW       48
#define UOPC_SD       49
#define UOPC_ADDI     50
#define UOPC_SLLI     51
#define UOPC_SLTI     52
#define UOPC_SLTIU    53
#define UOPC_XORI     54
#define UOPC_SRLI     55
#define UOPC_SRAI     56
#define UOPC_ORI      57
#define UOPC_ANDI     58
#define UOPC_ADDIW    59
#define UOPC_SLLIW    60
#define UOPC_SRLIW    61
#define UOPC_SRAIW    62
#define UOPC_FENCE    63
#define UOPC_FENCEI   64
#define UOPC_ECALL    65
#define UOPC_EBREAK   66
#define UOPC_CSRRW    67
#define UOPC_CSRRS    68
#define UOPC_CSRRC    69
#define UOPC_CSRRWI   70
#define UOPC_CSRRSI   71
#define UOPC_CSRRCI   72
#define UOPC_MRET     118
#define UOPC_WFI      120
#define UOPC_ILLEGAL  255

static uint32_t extract_imm_i(uint32_t inst) { int32_t v=(int32_t)(inst)>>20; return (uint32_t)v; }
static uint32_t extract_imm_s(uint32_t inst) {
    int32_t v=((int32_t)(inst)>>20)&0xFFFFFE0; v|=(inst>>7)&0x1F; if(v&0x800) v|=0xFFFFF000; return (uint32_t)v; }
static uint32_t extract_imm_b(uint32_t inst) {
    int32_t v=((inst>>8)&0xF)<<1; v|=((inst>>25)&0x3F)<<5; v|=((inst>>7)&0x1)<<11; v|=((inst>>31)&0x1)<<12;
    if(v&0x1000) v|=0xFFFFE000; return (uint32_t)v; }
static uint32_t extract_imm_u(uint32_t inst) { return inst&0xFFFFF000; }
static uint32_t extract_imm_j(uint32_t inst) {
    int32_t v=((inst>>21)&0x3FF)<<1; v|=((inst>>20)&0x1)<<11; v|=((inst>>12)&0xFF)<<12; v|=((inst>>31)&0x1)<<20;
    if(v&0x100000) v|=0xFFE00000; return (uint32_t)v; }

void decode_module(BoomCoreState& state) {
    DecodeState& dec = state.decode;
    dec.dec_valids[0] = false;

    if (state.global_flush) return;
    if (!state.frontend.fetch_packet_valid) return;

    uint64_t pc = state.frontend.fetch_uop.debug_pc;
    uint32_t inst = state.frontend.fetch_uop.inst;

    MicroOp uop;
    uop.inst = inst;
    uop.debug_pc = pc;
    uop.rename.lrs1 = (inst>>15)&0x1F;
    uop.rename.lrs2 = (inst>>20)&0x1F;
    uop.rename.ldst = (inst>>7)&0x1F;
    uop.branch.pc_lob = pc & 0x3F;

    uint8_t opcode = inst & 0x7F;
    uint8_t f3 = (inst>>12)&0x7;
    uint8_t f7 = (inst>>25)&0x7F;
    uint8_t rd = (inst>>7)&0x1F;

    switch (opcode) {
        case 0x37: uop.uopc=UOPC_LUI; uop.iq_type=IQ_ALU; uop.fu_code= FU_ALU;
            uop.ctrl.op1_sel=OP1_X0; uop.ctrl.op2_sel=OP2_IMU; uop.imm_packed=extract_imm_u(inst);
            uop.rename.dst_rtype=DST_INT; break;
        case 0x17: uop.uopc=UOPC_AUIPC; uop.iq_type=IQ_ALU; uop.fu_code= FU_ALU;
            uop.ctrl.op1_sel=OP1_PC; uop.ctrl.op2_sel=OP2_IMU; uop.imm_packed=extract_imm_u(inst);
            uop.rename.dst_rtype=DST_INT; break;
        case 0x6F: uop.uopc=UOPC_JAL; uop.iq_type=IQ_ALU; uop.fu_code= FU_ALU;
            uop.ctrl.op1_sel=OP1_PC; uop.ctrl.op2_sel=OP2_IMM; uop.ctrl.br_type=BR_J;
            uop.imm_packed=extract_imm_j(inst); uop.rename.dst_rtype=(rd!=0)?DST_INT:DST_X0;
            uop.branch.is_jal=true; break;
        case 0x67: uop.uopc=UOPC_JALR; uop.iq_type=IQ_ALU; uop.fu_code= FU_ALU;
            uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_IMM; uop.ctrl.br_type=BR_JR;
            uop.imm_packed=extract_imm_i(inst); uop.rename.dst_rtype=(rd!=0)?DST_INT:DST_X0;
            uop.branch.is_jalr=true; break;
        case 0x63: uop.iq_type=IQ_ALU; uop.fu_code= FU_ALU;
            uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_RS2; uop.imm_packed=extract_imm_b(inst);
            uop.branch.is_br=true; uop.rename.dst_rtype=DST_N;
            switch(f3) { case 0:uop.uopc=UOPC_BEQ;uop.ctrl.br_type=BR_EQ;break;
            case 1:uop.uopc=UOPC_BNE;uop.ctrl.br_type=BR_NE;break;
            case 4:uop.uopc=UOPC_BLT;uop.ctrl.br_type=BR_LT;break;
            case 5:uop.uopc=UOPC_BGE;uop.ctrl.br_type=BR_GE;break;
            case 6:uop.uopc=UOPC_BLTU;uop.ctrl.br_type=BR_LTU;break;
            case 7:uop.uopc=UOPC_BGEU;uop.ctrl.br_type=BR_GEU;break;
            default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;uop.exc_cause=2;break;} break;
        case 0x03: uop.iq_type=IQ_MEM; uop.fu_code= FU_MEM;
            uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_IMM; uop.ctrl.is_load=true;
            uop.imm_packed=extract_imm_i(inst); uop.rename.dst_rtype=DST_INT;
            switch(f3) { case 3:uop.uopc=UOPC_LD;uop.mem.mem_size=3;break;
            default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;uop.exc_cause=2;break;} break;
        case 0x23: uop.iq_type=IQ_MEM; uop.fu_code= FU_MEM;
            uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_RS2; uop.ctrl.is_sta=true;
            uop.imm_packed=extract_imm_s(inst); uop.mem.uses_stq=true; uop.rename.dst_rtype=DST_N;
            switch(f3) { case 3:uop.uopc=UOPC_SD;uop.mem.mem_size=3;break;
            default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;uop.exc_cause=2;break;} break;
        case 0x13: uop.iq_type=IQ_ALU; uop.fu_code= FU_ALU;
            uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_IMM; uop.imm_packed=extract_imm_i(inst);
            uop.rename.dst_rtype=DST_INT;
            switch(f3) { case 0:uop.uopc=UOPC_ADDI;break;
            case 2:uop.uopc=UOPC_SLTI;break; case 3:uop.uopc=UOPC_SLTIU;break;
            case 4:uop.uopc=UOPC_XORI;break; case 6:uop.uopc=UOPC_ORI;break;
            case 7:uop.uopc=UOPC_ANDI;break;
            case 1:uop.uopc=UOPC_SLLI;break;
            case 5:uop.uopc=(f7==0)?UOPC_SRLI:UOPC_SRAI;break;
            default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;break;} break;
        case 0x1B: uop.iq_type=IQ_ALU; uop.fu_code= FU_ALU;
            uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_IMM; uop.imm_packed=extract_imm_i(inst);
            uop.ctrl.fcn_dw=1; uop.rename.dst_rtype=DST_INT;
            switch(f3) { case 0:uop.uopc=UOPC_ADDIW;break;
            case 1:uop.uopc=UOPC_SLLIW;break;
            case 5:uop.uopc=(f7==0)?UOPC_SRLIW:UOPC_SRAIW;break;
            default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;break;} break;
        case 0x33: uop.iq_type=IQ_ALU; uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_RS2;
            if (f7==1) { uop.fu_code= FU_MUL; uop.rename.dst_rtype=DST_INT;
                switch(f3) { case 0:uop.uopc=UOPC_MUL;break;
                default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;break;}}
            else { uop.fu_code= FU_ALU; uop.rename.dst_rtype=DST_INT;
                switch(f3) { case 0:uop.uopc=(f7==0x20)?UOPC_SUB:UOPC_ADD;break;
                case 1:uop.uopc=UOPC_SLL;break; case 2:uop.uopc=UOPC_SLT;break;
                case 3:uop.uopc=UOPC_SLTU;break; case 4:uop.uopc=UOPC_XOR;break;
                case 5:uop.uopc=(f7==0x20)?UOPC_SRA:UOPC_SRL;break;
                case 6:uop.uopc=UOPC_OR;break; case 7:uop.uopc=UOPC_AND;break;
                default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;break;}} break;
        case 0x3B: uop.iq_type=IQ_ALU; uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_RS2;
            uop.fu_code= FU_ALU; uop.rename.dst_rtype=DST_INT; uop.ctrl.fcn_dw=1;
            switch(f3) { case 0:uop.uopc=(f7==0x20)?UOPC_SUBW:UOPC_ADDW;break;
            case 1:uop.uopc=UOPC_SLLW;break;
            case 5:uop.uopc=(f7==0x20)?UOPC_SRAW:UOPC_SRLW;break;
            default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;break;} break;
        case 0x0F: uop.uopc=UOPC_FENCE; uop.iq_type=IQ_MEM; uop.fu_code= FU_MEM;
            uop.rename.dst_rtype=DST_N; break;
        case 0x73: if(f3==0) { if(rd==0&&(inst>>20)==0) {uop.uopc=UOPC_ECALL;
            uop.iq_type=IQ_ALU; uop.fu_code= FU_CSR; uop.exception=true; uop.exc_cause=11;
            uop.is_sys_pc2epc=true;} else {uop.uopc=UOPC_MRET; uop.iq_type=IQ_ALU;
            uop.fu_code= FU_CSR; uop.rename.dst_rtype=DST_N;}}
            else { uop.iq_type=IQ_ALU; uop.fu_code= FU_CSR;
            uop.ctrl.op1_sel=OP1_RS1; uop.ctrl.op2_sel=OP2_IMZ;
            uop.csr_addr=inst>>20; uop.rename.dst_rtype=DST_INT;
            switch(f3) { case 1:uop.uopc=UOPC_CSRRW;uop.ctrl.csr_cmd=CSR_W;break;
            case 2:uop.uopc=UOPC_CSRRS;uop.ctrl.csr_cmd=CSR_S;break;
            case 3:uop.uopc=UOPC_CSRRC;uop.ctrl.csr_cmd=CSR_C;break;
            case 5:uop.uopc=UOPC_CSRRWI;uop.ctrl.csr_cmd=CSR_W;break;
            case 6:uop.uopc=UOPC_CSRRSI;uop.ctrl.csr_cmd=CSR_S;break;
            case 7:uop.uopc=UOPC_CSRRCI;uop.ctrl.csr_cmd=CSR_C;break;
            default:uop.uopc=UOPC_ILLEGAL;uop.exception=true;break;}} break;
        default: uop.uopc=UOPC_ILLEGAL; uop.exception=true; uop.exc_cause=2; uop.iq_type=IQ_ALU; uop.fu_code=FU_ALU; break;
    }

    if (uop.uopc==UOPC_ILLEGAL && !uop.exception) { uop.exception=true; uop.exc_cause=2; }

    dec.dec_uops[0] = uop;
    dec.dec_valids[0] = true;
}

}

// ==== rename.cpp ====

namespace boom {

void rename_module(BoomCoreState& state) {
    RenameState& ren = state.rename;
    RenameMapTableState& mt = ren.int_map_table;
    RenameFreeListState& fl = ren.int_free_list;

    for (int i=0; i<DISPATCH_WIDTH; i++) {
        ren.renamed_valids[i]=false; ren.renamed_uops[i]=MicroOp();
    }
    if (state.global_flush) return;

    if (state.brupdate.valid && state.brupdate.mispredict) {
        for (int i=0; i<LOGICAL_REG_COUNT; i++) {
            mt.map_table[i] = mt.committed_map_table[i];
            for (int j=0; j<MAX_BRANCH_COUNT; j++) mt.br_snapshots[i][j]=mt.committed_map_table[i];
        }
    }

    for (int i=0; i<DISPATCH_WIDTH; i++) {
        if (!state.decode.dec_valids[i]) continue;
        MicroOp uop = state.decode.dec_uops[i];

        uop.rename.prs1 = mt.map_table[uop.rename.lrs1];
        uop.rename.prs2 = mt.map_table[uop.rename.lrs2];
        uop.rename.stale_pdst = mt.map_table[uop.rename.ldst];

        uop.rename.prs1_busy = false;
        uop.rename.prs2_busy = false;

        if (uop.rename.dst_rtype == DST_INT && uop.rename.ldst != 0) {
            if (fl.count > 0) {
                uint8_t pdst = fl.free_list[fl.head];
                fl.head = (fl.head+1)%INT_PHYS_REGS; fl.count--;
                fl.busy_table[pdst] = true;
                uop.rename.pdst = pdst;
                mt.map_table[uop.rename.ldst] = pdst;
            }
        } else { uop.rename.pdst = 0; uop.rename.ldst = 0; }

        ren.renamed_uops[i] = uop;
        ren.renamed_valids[i] = true;
    }
}

}

// ==== issue.cpp ====

namespace boom {

void issue_module(BoomCoreState& state) {
    IssueState& iss = state.issue;
    const RenameState& ren = state.rename;

    for (int i=0; i<ISSUE_WIDTH; i++) { iss.issued_valids[i]=false; iss.issued_uops[i]=MicroOp(); }

    if (state.global_flush) {
        for (int j=0; j<ISSUE_QUEUE_ALU_DEPTH; j++) iss.alu_iq.entries[j].valid=false;
        iss.alu_iq.count=0; iss.alu_iq.head=0; iss.alu_iq.tail=0; return;
    }

    for (int i=0; i<DISPATCH_WIDTH; i++) {
        if (!ren.renamed_valids[i]) continue;
        if (iss.alu_iq.count >= ISSUE_QUEUE_ALU_DEPTH) break;
        const MicroOp& uop = ren.renamed_uops[i];
        if (uop.iq_type != IQ_ALU) continue;
        IssueSlotEntry& slot = iss.alu_iq.entries[iss.alu_iq.tail];
        slot.valid=true; slot.request=true; slot.granted=false; slot.killed=false;
        slot.uop=uop; slot.prs1_busy=uop.rename.prs1_busy;
        slot.prs2_busy=uop.rename.prs2_busy; slot.pdst_busy=false;
        iss.alu_iq.tail=(iss.alu_iq.tail+1)%ISSUE_QUEUE_ALU_DEPTH; iss.alu_iq.count++;
    }

    int issued=0;
    const int implemented_alu_lanes = DISPATCH_WIDTH;
    for (int i=0; i<ISSUE_QUEUE_ALU_DEPTH && issued<ISSUE_WIDTH && issued<implemented_alu_lanes; i++) {
        IssueSlotEntry& s = iss.alu_iq.entries[i];
        if (s.valid && s.request && !s.killed && !s.prs1_busy && !s.prs2_busy && !s.pdst_busy) {
            s.granted=true; s.request=false;
            iss.issued_uops[issued]=s.uop; iss.issued_valids[issued]=true; issued++;
        }
    }

    IssueSlotEntry temp[ISSUE_QUEUE_ALU_DEPTH];
    int w=0;
    for (int i=0; i<ISSUE_QUEUE_ALU_DEPTH; i++) {
        if (iss.alu_iq.entries[i].valid && !iss.alu_iq.entries[i].granted)
            temp[w++]=iss.alu_iq.entries[i];
    }
    for (int i=w; i<ISSUE_QUEUE_ALU_DEPTH; i++) temp[i].valid=false;
    for (int i=0; i<ISSUE_QUEUE_ALU_DEPTH; i++) iss.alu_iq.entries[i]=temp[i];
    iss.alu_iq.tail=w%ISSUE_QUEUE_ALU_DEPTH; iss.alu_iq.count=w;
}

}

// ==== execute.cpp ====

namespace boom {

static uint64_t sext32(int64_t v) { return (uint64_t)((int32_t)(v&0xFFFFFFFF)); }

void execute_module(BoomCoreState& state) {
    ExecuteState& exe = state.execute;
    const IssueState& iss = state.issue;

    for (int i=0; i<DISPATCH_WIDTH; i++) exe.alu_results[i].valid=false;

    int ri=0;
    for (int i=0; i<ISSUE_WIDTH && ri<DISPATCH_WIDTH; i++) {
        if (!iss.issued_valids[i]) continue;
        const MicroOp& uop = iss.issued_uops[i];

        uint64_t rs1 = (uop.rename.prs1!=0) ? state.int_rf[uop.rename.prs1] : 0;
        uint64_t rs2 = (uop.rename.prs2!=0) ? state.int_rf[uop.rename.prs2] : 0;
        uint64_t pc = uop.debug_pc;

        int64_t op1=(int64_t)rs1, op2=(int64_t)rs2;
        if (uop.ctrl.op1_sel==OP1_PC) op1=(int64_t)pc;
        if (uop.ctrl.op2_sel==OP2_IMM||uop.ctrl.op2_sel==OP2_IMZ) op2=(int64_t)(int32_t)uop.imm_packed;
        if (uop.ctrl.op2_sel==OP2_IMU) op2=(int64_t)uop.imm_packed;

        ExecuteState::AluResult& r = exe.alu_results[ri];
        r.valid=true; r.uop=uop; r.exception=false; r.mispredict=false; r.result=0;

        switch (uop.uopc) {
            case 1: case 50: r.result=(uint64_t)(op1+op2); break;
            case 2: r.result=(uint64_t)(op1-op2); break;
            case 3: case 51: r.result=op1<<(op2&0x3F); break;
            case 4: case 52: r.result=(op1<op2)?1:0; break;
            case 5: case 53: r.result=(rs1<rs2)?1:0; break;
            case 6: case 54: r.result=op1^op2; break;
            case 7: case 55: r.result=rs1>>(op2&0x3F); break;
            case 8: case 56: r.result=op1>>(op2&0x3F); break;
            case 9: case 57: r.result=op1|op2; break;
            case 10: case 58: r.result=op1&op2; break;
            case 11: case 59: r.result=sext32((int64_t)((int32_t)rs1+(int32_t)uop.imm_packed)); break;
            case 12: r.result=sext32((int64_t)((int32_t)rs1-(int32_t)rs2)); break;
            case 13: case 60: r.result=sext32((int64_t)((int32_t)rs1<<((int32_t)(uop.imm_packed&0x1F)))); break;
            case 15: case 62: r.result=sext32((int64_t)((int32_t)rs1>>((int32_t)(uop.imm_packed&0x1F)))); break;
            case 16: r.result=(int64_t)((int32_t)rs1)*(int64_t)((int32_t)rs2); break;
            case 29: r.result=pc+4; r.mispredict=true; r.redirect_pc=(uint64_t)((int64_t)pc+(int64_t)(int32_t)uop.imm_packed); break;
            case 30: r.result=pc+4; r.mispredict=true; r.redirect_pc=(rs1+(int64_t)(int32_t)uop.imm_packed)&~1ULL; break;
            case 31: r.mispredict=(rs1==rs2); r.redirect_pc=pc+(int64_t)(int32_t)uop.imm_packed; break;
            case 32: r.mispredict=(rs1!=rs2); r.redirect_pc=pc+(int64_t)(int32_t)uop.imm_packed; break;
            case 33: r.mispredict=((int64_t)rs1<(int64_t)rs2); r.redirect_pc=pc+(int64_t)(int32_t)uop.imm_packed; break;
            case 34: r.mispredict=((int64_t)rs1>=(int64_t)rs2); r.redirect_pc=pc+(int64_t)(int32_t)uop.imm_packed; break;
            case 35: r.mispredict=(rs1<rs2); r.redirect_pc=pc+(int64_t)(int32_t)uop.imm_packed; break;
            case 36: r.mispredict=(rs1>=rs2); r.redirect_pc=pc+(int64_t)(int32_t)uop.imm_packed; break;
            case 37: r.result=uop.imm_packed; break;
            case 38: r.result=pc+uop.imm_packed; break;
            case 67: case 68: case 69: case 70: case 71: case 72: r.result=0; break;
            default: r.result=0; break;
        }

        if (uop.exception) { r.exception=true; r.exc_cause=uop.exc_cause; }

        if (r.valid && uop.rename.dst_rtype==DST_INT && uop.rename.pdst!=0) {
            state.int_rf[uop.rename.pdst] = r.result;
        }
        ri++;
    }
}

}

// ==== branch.cpp ====

namespace boom {

void branch_module(BoomCoreState& state) {
    for (int i=0; i<DISPATCH_WIDTH; i++) {
        if (!state.execute.alu_results[i].valid) continue;
        const ExecuteState::AluResult& r = state.execute.alu_results[i];
        if (r.mispredict && (r.uop.branch.is_br || r.uop.branch.is_jal || r.uop.branch.is_jalr)) {
            state.brupdate.valid = true;
            state.brupdate.mispredict = true;
            state.brupdate.jalr_target = r.redirect_pc;
            state.brupdate.mispredict_mask = 1;
        }
    }
}

}

// ==== lsu.cpp ====

namespace boom {
void lsu_module(BoomCoreState& state) { (void)state; }
}

namespace boom {
void commit_module(BoomCoreState& state) { (void)state; }
}

// ==== csr.cpp ====

namespace boom {

void csr_module(BoomCoreState& state) {
    state.csr.cycle = state.csr.cycle + 1;
}

}

// ==== boom_core_step.cpp ====

namespace boom {
extern void frontend_module(BoomCoreState& state, PipeSignals& pipe);
extern void decode_module(BoomCoreState& state);
extern void rename_module(BoomCoreState& state);
extern void issue_module(BoomCoreState& state);
extern void execute_module(BoomCoreState& state);
extern void branch_module(BoomCoreState& state);
extern void lsu_module(BoomCoreState& state);
extern void csr_module(BoomCoreState& state);
static void rob_allocate(BoomCoreState& state);
void rob_commit_module(BoomCoreState& state, PipeSignals& pipe);

static void rob_allocate(BoomCoreState& state) {
    RobInternalState& rob = state.rob;
    if (rob.state == ROB_INIT) rob.state = ROB_NORMAL;
    if (state.global_flush) return;
    for (int i=0; i<DISPATCH_WIDTH; i++) {
        if (!state.rename.renamed_valids[i]) continue;
        bool is_full = (rob.head==rob.tail) && rob.maybe_full;
        if (is_full) { state.rename.renamed_valids[i]=false; break; }
        MicroOp uop = state.rename.renamed_uops[i];
        if (uop.uopc == 0) continue;
        RobEntry& entry = rob.entries[rob.tail];
        entry.valid=true; entry.busy=true; entry.exception=uop.exception;
        uop.queue.rob_idx = rob.tail; entry.uop = uop;
        state.rename.renamed_uops[i].queue.rob_idx = rob.tail;
        rob.tail=(rob.tail+1)%ROB_DEPTH;
        if (rob.tail==rob.head) rob.maybe_full=true;
    }
}

void rob_commit_module(BoomCoreState& state, PipeSignals& pipe) {
    RobInternalState& rob = state.rob;
    rob.commit_valid = false;

    if (state.brupdate.valid && state.brupdate.mispredict) {
        for (int i=0; i<ROB_DEPTH; i++) {
            if (rob.entries[i].valid) { rob.entries[i].valid=false; rob.entries[i].busy=false; }
        }
        rob.head=0; rob.tail=0; rob.maybe_full=false; rob.state=ROB_NORMAL;
        state.global_flush = true; return;
    }
    for (int i=0; i<DISPATCH_WIDTH; i++) {
        if (!state.execute.alu_results[i].valid) continue;
        const ExecuteState::AluResult& r = state.execute.alu_results[i];
        uint8_t ridx = r.uop.queue.rob_idx;
        if (ridx<ROB_DEPTH && rob.entries[ridx].valid) {
            rob.entries[ridx].busy=false;
            if (r.exception) rob.entries[ridx].exception=true;
        }
    }
    bool is_empty = (rob.head==rob.tail) && !rob.maybe_full;
    if (!is_empty && rob.entries[rob.head].valid && !rob.entries[rob.head].busy) {
        RobEntry& he = rob.entries[rob.head];
        MicroOp& uop = he.uop;
        if (he.exception) {
            if (uop.uopc == 65) {
                uint8_t a0_pdst = state.rename.int_map_table.map_table[10];
                uint64_t a0_val = (a0_pdst!=0) ? state.int_rf[a0_pdst] : 0;
                if (a0_val==0) state.io_success = true;
                else state.io_trap = true;
                he.valid=false; rob.head=(rob.head+1)%ROB_DEPTH; rob.maybe_full=false;
            } else { rob.state = ROB_EXCEPTION; state.io_trap = true; }
        } else {
            state.csr.instret++;
            CommitEntry ce;
            ce.valid=true; ce.pc=uop.debug_pc; ce.inst=uop.inst;
            ce.rd_valid=(uop.rename.dst_rtype==DST_INT && uop.rename.pdst!=0);
            ce.rd=uop.rename.ldst; ce.priv=state.csr.priv;
            ce.exception=false; ce.branch_mispredict=false;
            ce.rd_value=ce.rd_valid ? state.int_rf[uop.rename.pdst] : 0;
            if (uop.rename.pdst!=0) {
                state.rename.int_map_table.committed_map_table[uop.rename.ldst]=uop.rename.pdst;
                if (uop.rename.stale_pdst!=0 && uop.rename.stale_pdst<INT_PHYS_REGS) {
                RenameFreeListState& fl=state.rename.int_free_list;
                if (fl.count<INT_PHYS_REGS) {
                    fl.busy_table[uop.rename.stale_pdst]=false;
                    fl.free_list[fl.tail]=uop.rename.stale_pdst;
                    fl.tail=(fl.tail+1)%INT_PHYS_REGS; fl.count++;
                }
            }
            }
            if (!pipe.commit_trace.full()) pipe.commit_trace.write(ce);
            rob.last_commit=ce; rob.commit_valid=true;
            he.valid=false; rob.head=(rob.head+1)%ROB_DEPTH; rob.maybe_full=false;
        }
    }
}

}

void boom_core_step(BoomCoreState& state, PipeSignals& pipe) {
    BoomCoreState next_state = state;
    next_state.global_flush = false;
    next_state.io_success = next_state.io_trap = false;
    next_state.brupdate.valid = next_state.brupdate.mispredict = false;

    boom::csr_module(next_state);
    boom::branch_module(next_state);
    boom::lsu_module(next_state);
    boom::frontend_module(next_state, pipe);
    boom::decode_module(next_state);
    boom::rename_module(next_state);
    boom::rob_allocate(next_state);
    boom::issue_module(next_state);
    boom::execute_module(next_state);
    boom::rob_commit_module(next_state, pipe);

    state = next_state;
}

// ==== boom_core_top.cpp ====

extern void boom_core_step(BoomCoreState& state, PipeSignals& pipe);

void boom_core_top(hls::stream<ImemRequest>&  imem_req_out,
                   hls::stream<ImemResponse>& imem_resp_in,
                   hls::stream<CommitEntry>&  commit_trace_out,
                   bool& io_success,
                   bool& io_halted,
                   bool& io_trap,
                   bool& io_cycle_valid,
                   uint64_t& io_cycle,
                   uint64_t& io_instret) {
#pragma HLS INTERFACE ap_ctrl_none port=return
#pragma HLS INTERFACE axis port=imem_req_out
#pragma HLS INTERFACE axis port=imem_resp_in
#pragma HLS INTERFACE axis port=commit_trace_out
#pragma HLS INTERFACE ap_none port=io_success
#pragma HLS INTERFACE ap_none port=io_halted
#pragma HLS INTERFACE ap_none port=io_trap
#pragma HLS INTERFACE ap_none port=io_cycle_valid
#pragma HLS INTERFACE ap_none port=io_cycle
#pragma HLS INTERFACE ap_none port=io_instret

    static BoomCoreState state;
#pragma HLS RESET variable=state

    PipeSignals pipe;

CORE_CYCLE:
    while (true) {
#pragma HLS PIPELINE II=1

        if (!imem_resp_in.empty() && !pipe.imem_resp.full())
            pipe.imem_resp.write(imem_resp_in.read());

        boom_core_step(state, pipe);

        if (!pipe.imem_req.empty())
            imem_req_out.write(pipe.imem_req.read());
        if (!pipe.commit_trace.empty())
            commit_trace_out.write(pipe.commit_trace.read());

        io_success = state.io_success;
        io_halted = state.io_halted;
        io_trap = state.io_trap;
        io_cycle_valid = true;
        io_cycle = state.csr.cycle;
        io_instret = state.csr.instret;
    }
}
